### ISSUE TITLE
adding a "layer of indirection" for browsing/editing pads

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#100]
Adding a LAYER OF INDIRECTION to Etherpad, so that ALL
pads gets served into ONE url?  This would be very helpful
for gadgetized versions of the program (especially with
wiki style links). -- This is similar to the idea of making
Etherpad into a set of "portlets".

**Comment by holtzermann17** [comment]
Marking as high priority, since this is something I personally would want to work on.

**Comment by sesam** [comment]
I suspect it would be easy to change the pad name detection from (supersite)/(padname) to (supersite)/?padname or (supersite)/open?pad=padname or similar.
