### ISSUE TITLE
everything public by default (and other similar settings)

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#101]
Everything-public-by-default: no (setting in etherpad properties file),
Everything-writable-by-default: no (similar)
Typical-read-writableness: none/readable/writable

Search functionality should take these settings into account.

**Comment by holtzermann17** [comment]
Marking as high priority because it just makes sense.

**Comment by holtzermann17** [comment]
Marking as assigned to me.  John is interested in this too, especially if it can give an RSS feed of existing pads.

**Comment by JohnMcLear** [comment]
+1

**Comment by johnuren1980** [comment]
+1 please and for me quite an important feature

**Comment by redhog** [comment]
Note that this is only to allow public/private distinction in the absence of twitterStyleTags! If that plugin is installed, this would allow you not to have to add #public (and/or #writable) to your pads and still have them public, to force public if you want. Default values however comes from the default content of a pad, which can be easily changed already.
