### ISSUE TITLE
Security: Admin Menu should be protected by default 

### ISSUE THREAD

**Issue by brianherman** [ether/pad#105]
A default install should make sure that the admin menu is protected.
One possibility is to auto-create a password and output this password to the terminal while starting up the first time. Saving the password in the .properties file used and showing instructions on the admin menu "enter password-screen" on where the password can be found/edited could be a very useful bonus feature.

Prompted by:
I have just noticed that the admin menu doesn't have a login or password.
How would one approach this problem?
--Brian James Herman
UIC & UofC (consultant)

**Comment by sesam** [comment]
I beleive the password should be in the .properties file you use for your site. Please have a look there.

**Comment by cjb** [comment]
Enable production mode.  ("etherpad.isProduction = true")

**Comment by holtzermann17** [comment]
I think that closes the issue.

**Comment by brianherman** [comment]
Thanks a bunch!

**Comment by redhog** [comment]
I'm marking this as Installation, as it's actually a problem with the debian packaging, not with the code.
