### ISSUE TITLE
Plugin Installation

### ISSUE THREAD

**Issue by brianherman** [ether/pad#106]
There is something screwy going around with the plugin installation dialog.
What is it trying to do?
I click install and immediately goes to uninstall.

**Comment by holtzermann17** [comment]
These issues are fixed in recent versions of redhog/pad.

**Comment by holtzermann17** [comment]
But note that at least one related bug remains, cf.
http://li101-104.members.linode.com:9000/landing

**Comment by holtzermann17** [comment]
Sorry, please use the url http://metameso.org:9000/landing now (same page new URL).

**Comment by redhog** [comment]
Fixed in c375b9ee9363ea4e2f0a22439684741fae718bce

**Comment by holtzermann17** [comment]
I confirm that it works for me -- thanx Egil :)

http://metameso.org:8080/new-landing (has all current plugins installed and working fine)

**Comment by redhog** [comment]
Note: The plugin API has changes slightly to acommodate this fix...
