### ISSUE TITLE
clear pad history

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#111]
In case people have discussed things in the pad that are confidential, it could be useful to zap previous versions and just show the version where the confidential stuff has been erased as "version 1".  (I realize this could also be done by copy, paste, plus delete the old pad.)

**Comment by redhog** [comment]
This is a major security risk, as people could delete other peoples content (who owns non-pro content btw?). The only way I can think of is that the creator of a pad is given a special "management URL" for that pad, and that erasure/history forging can be done using that URL. But it's still scary.

**Comment by JohnMcLear** [comment]
Conflicts with http://github.com/ether/pad/issues#issue/22

**Comment by sesam** [comment]
The beginnings of the SQL needed to nuke one specific pad, history and all except for the last revision (though buggy) is at http://dtherpad.com/nuke
