### ISSUE TITLE
open certain classes of links in the same frame

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#112]
I have this in mind as something that would be useful for
wikiStyleLinks in particular, and especially in combination
with containers like Google Gadgets or Greasemonkey-created
frames.  However after playing around with this for a while,
I haven't been able to make it work for me.

Some notes on this are here: http://gist.github.com/450418

One other thing to mention is that this issue is a variant
of http://github.com/ether/pad/issues/100

**Comment by redhog** [comment]
There are two iframes within each other in Etherpad ACE.
The only way I can think of that'd make this work, is to send the frame name for the frame that etherpad is embedded in, as a URL parameter to etherpad.

Something like:

<iframe name="kafoo" src="http://localhost:9000/somepad?inframe=kafoo">

**Comment by holtzermann17** [comment]
...

   <iframe name="kafoo" src="http://localhost:9000/somepad?inframe=kafoo">

Yeah, I think that's the way to go.

**Comment by sesam** [comment]
The lost code from redhog should be:

Something like:
iframe name="kafoo" src="http://localhost:9000/somepad?inframe=kafoo"
