### ISSUE TITLE
etherpad should start after apt-get completes (execute init script)

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#114]
Issue from John; I think the idea is to run Etherpad as a service from /etc/init.d/etherpad ; so this way installation of etherpad would be similar to installing mysql or sshd or whatever.

**Comment by redhog** [comment]
Yes, it is installed in /etc/init.d/etherpad, but not started, as is standard on Debian/Ubuntu/RedHat for services. This will not be changed as it is done that way by all other services (sshd, apache etc) to improve security.
