### ISSUE TITLE
More documentation about the plugin system and how to create one etc

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#126]
The only current "documentation" of the plugin system is the set of existing examples.

**Comment by holtzermann17** [comment]
One thing that would help would help a lot would be documentation of how to get code to run client-side!  (With that in hand I can probably finish another example plugin ;).

Here's an example that _doesn't_ work, submitted for comment:
http://gist.github.com/465841

**Comment by sesam** [comment]
Also see tag #plugins on http://doc.etherpad.org/
