### ISSUE TITLE
distinguish between two plugins with the same name

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#127]
E.g. if you have two "test" plugins, the plugin system has no way to differentiate between them.  (One could argue that creating two different things with the same name is always a bad idea in programming, but still, the system should do the most "intelligent" thing when presented with screwy inputs!)

**Comment by holtzermann17** [comment]
I'm marking this as Milestone 1.2 since it doesn't seem like a "mission critical" bug and is more of an edge case.

**Comment by redhog** [comment]
How would you even put them in? A theme is named as a directoy inside the plugins directory... So, I see no problem here?

**Comment by holtzermann17** [comment]
good point :)
