### ISSUE TITLE
"core" version of etherpad

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#128]
Although we haven't defined just what we mean by a "core" version of etherpad, the basic
idea is to maximize performance.  There are probably multiple definitions of what a "core
etherpad" would _look_ like -- for example, maybe visually it would just consist of an editing
area.  This relates to the idea of rebuilding etherpad as a set of "portlets", discussed, e.g.,
at http://github.com/ether/pad/issues/100.

**Comment by redhog** [comment]
This is really two things in one - pluginizing various parts (maybe really just the chat) of what is currently the core etherpad, and changing the theme - see the minimal theme that somone added.
