### ISSUE TITLE
Writeup on Comet vs WebSockets

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#129]
WebSockets provides a way "to enable Web applications to maintain bidirectional communications with server-side processes".  It is supposed to work sort of like Voice over IP, and it should amount
to sending many fewer HTTP header bits and more actual content -- accordingly it should work
faster than the current Comet-based setup used by Etherpad.

See http://dev.w3.org/html5/websockets/

**Comment by redhog** [comment]
Yes, but it's only supported in very new webbrowsers (if any!!), so we need to hack this so that it can fallback to comet...
