### ISSUE TITLE
verbose "Loading..." mode for debugging

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#130]
It is really frustrating to see "Loading..." appear in a pad when the loading process hangs,
instead of some kind of trace or back-trace.  It would be great if we could create a "trace
function calls" mode for debugging purposes, and then create a verboseLoading option
in the etherpad.local.properties file that would cause the output of the trace to be sent to
loading pad in place of the "Loading..." message!!

**Comment by holtzermann17** [comment]
I want to work on this over the next week or so, because I'd like to get Etherpad and Rudel working together (http://github.com/scymtym/rudel), and this implies the need to understand what's really going on in Etherpad's server-client connection.  Furthermore, tracing function calls would be significantly useful in debugging other problems in the future.  I assigned this to me, but any help would be appreciated :)

**Comment by holtzermann17** [comment]
For client-side optimization (using IE):
http://ejohn.org/blog/deep-tracing-of-internet-explorer/

General-purpose stacktrace tool: http://github.com/emwendelin/javascript-stacktrace

**Comment by holtzermann17** [comment]
http://siliconforks.com/jscoverage/

**Comment by redhog** [comment]
http://github.com/emwendelin/javascript-stacktrace should probably be included in dev mode no matter what, and its handler set for document.onerror. This would allow debugging all sorts of strange problems, even non "loading..."-related ones, esp on non-firebug-enabled browsers.

**Comment by redhog** [comment]
Even better: Let's make this into a plugin that loads this and maybe even firebug light, but does not change the UI at all. Then it could even be dynamically enabled/disabled at run-time. Should be maybe an hours' work.

**Comment by redhog** [comment]
I have implemented (part of) this in two extensions: debugJsBacktrace and debugFirebugLite. I have also added another plugin, debugRaiseException that just adds a UI button to pads that raises an exception when clicked, to test the other two...
