### ISSUE TITLE
flickering and flashing in firefox on linux

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#131]
Sometimes (I'm not yet sure what triggers it), flashing appears in between the sidebar and
the editing area, or if the sidebar isn't there, then scrollbars appear and reappear about
once a second.

This error is printed repeatedly to the terminal window running firefox:

(firefox:29012): Gdk-WARNING **: Native children wider or taller than 65535 pixels are not supported

Perhaps interesting: the error prints _in duplicate_ every second.
This is with Firefox 3.5.7 for Ubuntu.

**Comment by holtzermann17** [comment]
A related error is seen with Gravpad running the micro theme -- the part of the scrollbar that indicates the visible portion of the document shrinks.  This is observed in both GDK and Aqua versions of Firefox (cf. http://metameso.org/~joe/tiny-scrollbar.png and http://metameso.org/~joe/another-tiny-scrollbar.tiff).  Judging by this behavior and the error message above, it seems that at least under some conditions (the micro theme?) Etherpad tries to become very tall!  Could this have something to do with the so-called magic dom?

**Comment by JohnMcLear** [comment]
http://github.com/ether/pad/issues#issue/24 & http://github.com/ether/pad/issues/issue/90#issue/90 & http://github.com/ether/pad/issues/issue/131

all same.  pick one and close other 2?
