### ISSUE TITLE
change INSTALL instructions to include openjdk option

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#132]
Someone has nicely uploaded instructions on how to build using openjdk to the
wiki, so it isn't strictly true that "Sun Java JDK 6" is the only way to satisfy the java
dependency.  See:

http://wiki.github.com/ether/pad/etherpad-building-installation-using-openjdk-instead-of-sun-java-jdk

This should go into INSTALL or perhaps we should create an INSTALL.openjdk file with suitable instructions for the openjdk bits.

**Comment by JohnMcLear** [comment]
Please clarify if Sun Java is needed or not, afaik it still is.

**Comment by redhog** [comment]
If it works with openjdk, including compilation, maybe we could even package it so that it can be run with either?

**Comment by JohnMcLear** [comment]
We prefer openjdk over sun java's?  I'm not savvy on the licensing issues.  Afaik OpenJDK is easier to deploy/install and has no license agreement.

**Comment by holtzermann17** [comment]
The last time I tried to install Etherpad Using OpenJDK (on Ubuntu 10.04) it didn't work.  Once upon a time, I was able to get it working with OpenJDK (I think that was on Fedora Core 8 or something along those lines).  Lots of unknowns at this point!

**Comment by jds2001** [comment]
I was able to get it running on F13 with OpenJDK, and didn't have to sacrifice any kittens in the process. The one problem that I did have was the version of Scala required, but there's another issue on that.

I think that documenting the fact that this will work is a good idea.

You need to set the JDK using alternatives before you do this:

as root:
alternatives --set java_sdk /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64
as your normal user:

#####

# You have to change following lines to your requirements:

#
export JAVA_HOME="/usr/lib/jvm/java/"
export SCALA_HOME="/usr/share/java/scala"
export SCALA_LIBRARY_JAR="/usr/share/java/scala/scala-library.jar"
export MYSQL_CONNECTOR_JAR="/usr/share/java/mysql-connector-java.jar"
export JAVA="/usr/lib/jvm/java/bin/java"
export SCALA="/usr/bin/scala"
export PATH="/usr/lib/jvm/java/bin:$PATH"
