### ISSUE TITLE
list pro pads on twitterStyleTags Home page

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#133]
A pad created in the pro domain foo.myhost.com:9000 that is tagged

  #public and #writeable

doesn't show up in foo.myhost.com:9000/ep/tag/
(even though this page exists), nor does it show up in myhost.com:9000/ep/tag

See also this issue: http://github.com/ether/pad/issues/101

**Comment by holtzermann17** [comment]
Note that the motd page shows up as "forbidden" on foo.myhost.com:9000/ep/tag/ ;)
Obviously messing with pro will take some work...

**Comment by redhog** [comment]
Pro and tagging is sort of... incompatible ideas really. Might take hard hacking AND designing to get working in any useful way...
