### ISSUE TITLE
(g)ui for switching themes

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#134]
Since we have a way to turn on and off plugins, we should probably have a corresponding way to switch themes.

**Comment by redhog** [comment]
Hm, true... Shouldn't be too hard to do, but requires that config to be stored in a new table in the DB.

Maybe we should move all config but the DB config to a tale in the DB in the future?

create table config (path varchar, value varchar);

where path is e.g. "etherpad.adminPassword"?
