### ISSUE TITLE
consistent look and feel but without pads

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#137]
We would like page.ejs not to include anything that is pad specific,
but still make all pages look like the pad pages, with editbar, docbar
and sidepane etc.

In short, we'd like to be able to put something in the central area of the
page -- that is not a pad.

**Comment by redhog** [comment]
Note that this mainly consists of extracting the resizing functions from pad2.js and its friends

**Comment by redhog** [comment]
This is a precondition for #117
