### ISSUE TITLE
Build time warnings

### ISSUE THREAD

**Issue by sesam** [ether/pad#138]
bin/build.sh
and
bin/rebuildjar.sh
could need some more hints on how to react to errors.
- rebuildjar seems to error out the first 1-2 times after a clean download for some ppl (occurred to me and on maillist + IRC long ago)
- John McLear had issues rebuilding while the apt-get install :ed version was running and perhaps some test or at least a warning in the relevant build scripts "Warning: Any running etherpad will prevent build from completing properly" 
  http://groups.google.com/group/etherpad-open-source-discuss/t/6e0ae57cef6b26f2

Or optionally make build scripts more robust and allow running one etherpad as a live site while building & compiling a developer version. Maybe Johns problem might boil down to java/scala/appjet stuff that runs on hardcoded ports?

**Comment by JohnMcLear** [comment]
Build script created, see issue 142.  This is an issue for 1.1 as all distro installs should be painless.
