### ISSUE TITLE
Replace MyISAM with InnoDB

### ISSUE THREAD

**Issue by sesam** [ether/pad#139]
InnoDB is more trustable to not break than MyISAM, which is important for Etherpad since we don't have any redudancy / data protection if the DB fails.

http://groups.google.com/group/etherpad-open-source-discuss/browse_thread/thread/ccfb6dc6a005b296

**Comment by redhog** [comment]
Note that there is generally only one thread - the collab server - that ever writes to the db. So it isn't as bad as it could be.

**Comment by JohnMcLear** [comment]
This will need doing at some point though.  In the future :P

**Comment by redhog** [comment]
And add transactions.... I have seen instances of broken pads after killing the pad server at the wrong moment (not very common, but still)
