### ISSUE TITLE
temporarily hide colors

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#14]
Locally (or globally) hide, but do not clear/delete, authorship information.

**Comment by dreeves** [comment]
You can already do this; it's in Pad Options.

**Comment by laughinghan** [comment]
The Pad Options thing only does it globally, and affects everyone's view of the pad. It'd be nice if you could just temporarily hide it for yourself.

**Comment by Kjue** [comment]
I agree, it would be beneficial to disable the colors momentarily. Some people like to use the pads with the colors while others almost detest them.

**Comment by theoryshaw** [comment]
(vote 1) or 'like'
