### ISSUE TITLE
log file/folder permissions check during startup

### ISSUE THREAD

**Issue by sesam** [ether/pad#140]
Some log file (or folder?) permissions tend to cause trouble for people starting up etherpad.

Can etherpad and/or startup scripts check the permissions and print warnings somewhere people will notice about permissions problems? Can it fix the permissions problem silently, or at least print a suggested command line on how to fix the permissions?

Mentioned here http://groups.google.com/group/etherpad-open-source-discuss/browse_thread/thread/8cd45922cee5e637  and one other recent mention on the maillist.

**Comment by redhog** [comment]
Please elaborate on the sets of permissions that causes problems (filenames, access rights)

**Comment by sesam** [comment]
Someone on the maillist had "a problem" and "solved" it by doing chmod -R 777 (path to etherpad logs folder)
I haven't tried to reproduce, but perhaps it shouldn't be hard to reproduce / add some simple tests+warnings inside log file startup code?
Hm, there's also the off chance the problem is with Jetty logs and not etherpad itself. That would mean tests have to move out to whatever (ba)sh script is used to start jetty.

**Comment by redhog** [comment]
Bwah. The apt package should obviously just have the right permissions. As for the rest of us, I guess the best we can do is check if the current user can write to the logs  dir - what the permissions "should" be is much dependent on the local sysadmin and his/her paranoialevel...

**Comment by redhog** [comment]
This has been fixed to the point where Etherpad now prints an error instead of just silently dying when this happens. Debian package still needs fixing though...

**Comment by redhog** [comment]
mkdir /var/log/etherpad
chown etherpad /var/log/etherpad
