### ISSUE TITLE
Install time hurdles (reverse-proxy, nginx)

### ISSUE THREAD

**Issue by sesam** [ether/pad#141]
A common problem on the maillist is that people can't get etherpad running through a proxy.
Perhaps this could be made easier? Is it taken care of in the apt -packaged etherpad?
John has a nginx config he want's to share -- let's get in included and referred to from an INSTALL text file.

**Comment by redhog** [comment]
Just put stuff like that in a contribs directory :)

**Comment by JohnMcLear** [comment]
This will go in during hackathon
