### ISSUE TITLE
Install time hurdles (superdomains)

### ISSUE THREAD

**Issue by sesam** [ether/pad#142]
People are having trouble adding hostnames to etherpad.local.properties -- or to globals.js(!?) as was the solution/workaround in this case: http://groups.google.com/group/etherpad-open-source-discuss/browse_thread/thread/bcfb0b4035c18422

In general this could be simplified or avoided by
1. Better defaults to make things work on localhost (and localhost ONLY) out of the box
2. make this a DB stored setting and some GUI that helps with adding/removing allowed superdomains

**Comment by JohnMcLear** [comment]
Noted, added to 1.1
