### ISSUE TITLE
export tickbox: "include colors"

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#144]
There should be a way to export the document and preserve the authorship information.

**Comment by redhog** [comment]
This, as well as preserving other styling (ref styling plugins), would be very useful for integration, where the exported HTML would be pulled by another system and included in some other webpage.

**Comment by holtzermann17** [comment]
In a related issue (side note): the logic of colors and "copy and paste" is interesting.  It seems that colors are preserved whenever _multiple_ colors are in the copied section, but changed whenever there is only _one_ color in the copied section.
