### ISSUE TITLE
compilation problems with scala 2.8.0

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#147]
Can we get some more specific information about what fails and what works?  See

http://groups.google.com/group/etherpad-open-source-discuss/browse_thread/thread/c69a86203e27b0d7

**Comment by sesam** [comment]
This issue could perhaps start with adding some warning about untested scala versions, including a link to some kind of living documentation (doc.etherpad.org somewhere?) on which scala versions are workable.

Another Scala version problem; a short thread
http://groups.google.com/group/etherpad-open-source-discuss/t/a74309c69885b1a3
which ended "Fixed it by downgrading to 2.7.4 Should have checked the forum first."

**Comment by JohnMcLear** [comment]
/usr/local/etherpad/infrastructure/net.appjet.bodylock/bodylock.scala:46: error: inferred type arguments [scala.collection.Map[String,String]{def empty: scala.collection.Map[String,String]{def empty: scala.collection.Map[String,String]{def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}; def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}; def companion: scala.collection.generic.GenericCompanion[Iterable[Any]{def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}]}] do not conform to method getOrElse's type parameter bounds [B >: scala.collection.mutable.SynchronizedMap[String,String]]
        val code = BodyLock.map.getOrElse(Map[String, String]()).getOrElse(elt.getFileName, "").split("\n"); // 0-indexed.
                                ^
/usr/local/etherpad/infrastructure/net.appjet.bodylock/bodylock.scala:64: error: inferred type arguments [scala.collection.Map[String,String]{def empty: scala.collection.Map[String,String]{def empty: scala.collection.Map[String,String]{def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}; def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}; def companion: scala.collection.generic.GenericCompanion[Iterable[Any]{def companion: scala.collection.generic.GenericCompanion[Iterable[Any]]}]}] do not conform to method getOrElse's type parameter bounds [B >: scala.collection.mutable.SynchronizedMap[String,String]]
      val code = BodyLock.map.getOrElse(Map[String, String]()).getOrElse(cause.sourceName(), "").split("\n"); // 0-indexed.
                              ^
/usr/local/etherpad/infrastructure/net.appjet.bodylock/bodylock.scala:150: error: not found: type byte
  def executableFromBytes(bytes: Array[byte], className: String) =
                                       ^
three errors found
/usr/local/etherpad/infrastructure/ace/bin/make:22: error: missing arguments for method collect in trait Iterator;
follow this method with `_' if you want to treat it as a partially applied function
    "@|[a-zA-Z0-9]+|[^@a-zA-Z0-9]{1,3}").r.findAllIn(input).collect.toArray;
                                                            ^
/usr/local/etherpad/infrastructure/ace/bin/make:46: error: missing arguments for method collect in trait Iterator;
follow this method with`_' if you want to treat it as a partially applied function
  }).collect:_*);
     ^
/usr/local/etherpad/infrastructure/ace/bin/make:49: error: value mkString is not a member of Array[Nothing]
  val afterReplace = toks.map(encode(_)).mkString.replaceAll(
                                         ^
three errors found
cp: cannot stat `/usr/local/etherpad/infrastructure/build/appjet.jar': No such file or directory

**Comment by ijuma** [comment]
See http://github.com/ether/pad/pull/179
