### ISSUE TITLE
Bypassing authentication for localhost in order to implement search

### ISSUE THREAD

**Issue by andreivolt** [ether/pad#148]
I'm trying to implement Nutch + Solr based search engine into my Etherpad installation. The main issue I'm having is that Nutch doesn't support `POST` authentication. Etherpad and Nutch are installed on the same machine, so an obvious solution would be to find a way to bypass authentication for `localhost`.

This is where I'm stuck. I don't know the Etherpad codebase very well, I've mostly done cosmetic tweaks until now. Can someone point me to where I should be looking, or potential solutions ? I've found some interesting bits of code having do to with auth in the codebase, but it's Javascript, so there's no obvious way to check if the request host is `localhost`.

Many thanks in advance and my apologies if I'm posting in the wrong place.

Andrei

**Comment by sesam** [comment]
There's the read-only pages that never needed authentication as far as I know?
Since this is an old issue, I'll close it now and will reopen if/when you take up this topic again. See you later?

**Comment by andreivolt** [comment]
Thanks, I've seen given up on the project, I think I was referring to
authentication for "pro" accounts.

+33(0)_6.13.71.67.66_ | @andreivolt http://twitter.com/andreivolt sur

## Twitter et un peu partout ailleurs

_Attention_\* : je ne vérifie cette boite qu'à 11h et 17h les jours ouvrés.
S'il y a urgence, **appelez-moi au +33(0)6.13.71.67.66**.*
