### ISSUE TITLE
fadeing colors

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#15]
Have authorship information fade out (i.e., newer edits have stronger colors).

**Comment by theoryshaw** [comment]
(vote 1) or 'like'

**Comment by theoryshaw** [comment]
...or have this concept incorporated in the 'timeslider' somehow.  Like such: http://dl.dropbox.com/u/7117445/sliderbar.jpg

Although, I think having this option in the 'edit mode', would be better.
