### ISSUE TITLE
very long document scrolling behaves oddly

### ISSUE THREAD

**Issue by puterleat** [ether/pad#150]
I have an 1800 line bibtex document which we want to edit in etherpad. 

However the edit window height appears to be limited to about 1400 lines — after that, the text is still pasted in ok but to access it requires selecting text and dragging below the bottom of the visible window - as though the div is overflowing.

Steps to reproduce:
1. Paste > 1500 lines of text into a pad
2. Try and edit the last line using the scrollbar

**Comment by xaocon** [comment]
I've noticed the same problem. I can't see anything under there. I can't get it to show at all below the line but I can copy text past the bottom of the line so the text is still there.

**Comment by Zir0h** [comment]
I'm pretty sure this is a dirty hack, but commenting out the following lines "fixed" it for me.

pad/infrastructure/ace/www/ace2_inner.js:  
//if (newHeight > 32000) newHeight = 32000;

pad/infrastructure/ace/www/ace2_inner.js:  
//if (newWidth > 32000) newWidth = 32000;

**Comment by Erode** [comment]
Observed the same problem.
The provided fix did not work.
My guess was about the quantity of text, at around ~>100ko it fails to render.
But its not explaining anything.

**Comment by Yuuji** [comment]
this is duplicated and is fixed since yesterday / today merge
