### ISSUE TITLE
packaging@etherpad.org is listed in github but fails.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/pad#154]
Egil needs to either setup/create mx or mailbox for this address.  it's listed on main github page.

**Comment by sesam** [comment]
Any news on this?

**Comment by JohnMcLear** [comment]
Still waiting on redhog

**Comment by redhog** [comment]
Oups... Assigning to me so I'll get it done :P

**Comment by Yuuji** [comment]
this is fixed, so the issue could be closed
