### ISSUE TITLE
Ability for pad admin to see an overview of all active pads

### ISSUE THREAD

**Issue by JohnMcLear** [ether/pad#155]
this would be a seperate page that displayed the Real time content of the pads being modified under their prodomain.

**Comment by holtzermann17** [comment]
this could presumably be made as an extension of my rtrc (realtimerecentchanges) plugin. (Since it is used for monitoring, we don't need it to accept input.)

**Comment by JohnMcLear** [comment]
This is true, input isn't a requirement.  It's more for reviewing what pupils are writing to ensure they are staying on topic :)

**Comment by holtzermann17** [comment]
Would be nice to do with a working version of the micro theme, which needs to be rewritten as we've discussed.  Waiting on an improved theme system.
