### ISSUE TITLE
/ep/admin doesn't require a password even though its set..

### ISSUE THREAD

**Issue by maf001** [ether/pad#158]
/ep/admin doesn't require a password even though its set..

From /ep/admin/config shows it as appjet.config.etherpad.adminPass = etherpadpassword

**Comment by redhog** [comment]
have you accidentally set devmode=true?
If so, that is the intended behaviour

**Comment by sesam** [comment]
And if so, then let's either rename this one, or create a new bug about adding this info directly in the UI. Something like "devmode is on, so the admin login is without password".

**Comment by maf001** [comment]
Checked my setup the devmode=false,

I installed from fresh using this commit: http://github.com/redhog/pad/commit/120bfd4e32817ff3ee27610d3d3e58bdd661bd8c

**Comment by redhog** [comment]
Ok, so this is a real bug then. Have you tried with an empty  / new database and a new install? Any specific steps to reproduce? Can someone else reproduce this?

**Comment by maf001** [comment]
This was a fresh VM i setup on, standard clean Debain install. I was testing with John.
