### ISSUE TITLE
Keep admin password in DB

### ISSUE THREAD

**Issue by sesam** [ether/pad#159]
The admin password should be stored in the DB, and deprecate saving it in the config file.

Motivation: avoid devmode confusion, make impossible deploying with default admin password, avoid publishing admin password when asking for help on a config file (all these things have already occured, and we'd like them to not occur again!)

Admin password should be easy to change through a command line trick. When admin login fails, this trick should be suggested and well visible.

Bonus: It could even be reasonable to run without password until the first non-localhost visitor uses a pad, and only after that start prompting on the admin-page "<a class"big red" href=...>Click here to set password</a>" as well as a row on the command line soon after startup. This way you could experiment and develop locally without minding about passwords, and then the password feature minds itself for your best interests when it actually starts being important. Good/bad idea?

This could be the a first step towards the general idea (I can't find its issue number?) about moving all settings into the database, and perhaps ask for database configuration interactively on first startup -- thereby eliminating the need altogether to manually create a configuration file.

**Comment by redhog** [comment]
The first part sounds like a good idea, but the second part, about moving all stuff into automated things, actually make it harder to automate for those who uses a packaging system, like Ubuntu/Debian.

**Comment by JohnMcLear** [comment]
I agree with the first part also (after I had a lesson from redhog)
