### ISSUE TITLE
copy text but keep authorship colours - useful for rollback of pad deletions!

### ISSUE THREAD

**Issue by zeigerpuppy** [ether/pad#160]
I noted an etherpad that had content deleted, I can see it in the history but if I paste from the timeline, it loses authoriship colours.  This may be best handled by a "revert to" feature in timeline (although this has its own problems allowing deletion of new content!).  however, I think the simplest way is to allow copy/paste to retain authorship colours.

**Comment by sesam** [comment]
I beleive copy&paste can hardly be made to preserve colors without a major effort.
There is also a Restore feature to be found under "Saved revisions" - assuming you did save a revision before deleting. So perhaps what we need to cover the use case is a feature to autocreate a revision when someone "deletes" a pad?

**Comment by redhog** [comment]
Maybe just allow restoring from arbitrary time-points, just not previously saved revisions? That'd probably be a rather simple feature to hack, compared to all the problems of author-preserving copy-paste.

**Comment by zeigerpuppy** [comment]
that would certainly solve the problem and provide a generally useful mechanism for rolling back edits if need be.
