### ISSUE TITLE
Remove the DNS wildcard requirement for pro pads

### ISSUE THREAD

**Issue by johnuren1980** [ether/pad#162]
I work for a governmental organisation and after following instructions for installing Etherpad, I got to start giving out pro pads when the admins said that they couldn't (and I checked, due to the design of the work intranet, they couldn't) do the DNS wildcard. Could pro-accounts not need the DNS configuration (the advantage is that companies could try etherpad including pro-accounts with little other network reconfiguration). Would /ep/team/<teamname> be a good place to put the team sites?

**Comment by JohnMcLear** [comment]
How urgent is this?  If you have budget we may be able to do it through one of our partner orgs however pro stuff isn't a priority unless we use it to fuel other contributions that affect a larger target audience.  Get in touch with me if you can and I will see what I can sort.

**Comment by JohnMcLear** [comment]
Note:  You can do pads on here.whatever.yourdomain.com  IE a.mypad.yourdomain.com & b.mypad.yourdomain.com
