### ISSUE TITLE
support for diffs to integrate off-line edits with author colours

### ISSUE THREAD

**Issue by zeigerpuppy** [ether/pad#163]
While most editing will be happening directly in etherpad, some users may need to take files off-line.
If the pad is edited between that time and when they put in their edits there may be a consistency problem.  It would be great if off-line edits could be diff'd with the pad (upload file and diff button maybe) and changes marked with the uploading author's colour after conflicts are approved.  This would create a simple mechanism for integrating off-line edits while keeping the pad structure and authorship consistent.

**Comment by sesam** [comment]
The difficulty here is to know when the offline copy started to diverge. Usually people choose a real and tried version control system when your kind of need arises. Have you looked at using git or hg (mercurial) or similar to cover your user story? Can you explain your use case some more?

**Comment by zeigerpuppy** [comment]
thanks for the comment, some more details:
User A, B and C are collaborating online on Day1:
text:
A: there were three white mice
B: changed:(three to four)
C: takes copy of text to edit offline

User C has to be offline Day2
A: changed (four to five)

C: edits (four to six) off-line

Day 3: User C returns
C wants to merge his changes with pad,
runs a diff which finds
conflict between (five/six)
C picks their edit as she know's it the correct change,
pad now shows the edit in the timeline with correct authorship
the rest of the text keeps author A

In this case there was not much fr C to look at and they could have just made the edit, but in a complex document, this mechanism would save a lot of time while ensuring changes can be tracked to the correct author.

Note that C could just have copied their entire text and replaced the pad, but then any other edits by A or B would have been lost.

Hope this little description illustrates the use of this procedure, personally I would be using it to ensure that an editor who takes the text offline can make comments and I can integrate them later even if I have worked on the document in the interim.
The problem with a versioning system is that it's nice for the pad to still be usable in real time.

**Comment by sesam** [comment]
ok, though I wasn't asking for how merging works :). I'll guess that your use case is called "collaborative text writing", and that ther may sometime but not always be a person C (your editor?) who has the final say.
Now imagine you're coming with your offline-edited text and wants to add your changes and get the changes of the others. You need to feed the system with
a) your text
b) what point in time that you had last "syncronized" online
c) some way to let person C decide which of your conflicting changes should stay or not. Perhaps C also wants to see all your changes.

You can build this as a plugin, but you need some serious programming skills and you probably have to learn the mathematics of operational transforms. Don't ask me how it works, it's quite complicated stuff. I'm adding labels Hard as hell and Plugins.

**Comment by zeigerpuppy** [comment]
I see your point, a proper off-line, on-line sync is non-trivial.
There may be a way to make it simpler, however.
for example (A as off line this time) perhaps feed:
a) your text (no timestamp)
Etherpad imports and stores A's off line edit file in 'pending' edit for admin user (C) to review

Then
etherpad shows diff between file import and current pad (which may have progressed by then) to C when they log in, with checkboxes next to lines/blocks for inclusion/exclusion
authorship colours maintained (as A in this case) once edits approved.

It's a sort of manual diff but may be much simpler to implement, also keeps a relatively sane timeline.

This sort of thing could be done manually off-line (eg: in textmate) but authorship colours would be lost.
