### ISSUE TITLE
Remove Sanselan or link to upstream version

### ISSUE THREAD

**Issue by sfreilich** [ether/pad#175]
Sanselan is huge and Etherpad uses it for almost nothing.  There's a working upstream version, so would be better to make that an external dependency.

**Comment by redhog** [comment]
What _do_ we use it for?

**Comment by JohnMcLear** [comment]
Sounds like working upstream is a good idea.

**Comment by sfreilich** [comment]
A proposed fix for removing Sanselan is at olin/pad@753cee0778c88f31f7ed.

Currently, Etherpad seems to use it only to generate a white one-by-one pixel tracking image, but it doesn't seem to use _that_ anywhere.

**Comment by redhog** [comment]
Merged all Olin college changes :)
