### ISSUE TITLE
padHierarchy has FOSS licensing issues

### ISSUE THREAD

**Issue by computercolin** [ether/pad#180]
I cannot take credit for these notes, DJ Gallagher (djsaurus) found this at the Olin Etherpad Activity Day
## DJ Status

Ran code against eclipse's validation/auto-build tools to check goodness of olin pad sources/packages and start understanding the plugin arch.

Ran a first pass of checking for sketchy licensing/includes in the plugins directory. Wasn't checking all the import statements so i missed some things. I did find one licensing problem:

the padHierarchy plugin, added in Redhog's working copy, depends on two files (jquerycssmenu.css and jquerycssmenu.js) taken from the dynamic drive css library (http://www.dynamicdrive.com/style/csslibrary/tos/ ). _THIS IS NON FREE CODE_ licensed by dumbbots/annoybots. I'd love to offer to replace it with custom ui code by us, but first I need a working instance so I can better examine what that code's doing.

http://github.com/ether/pad/tree/master/etherpad/src/plugins/padHierarchy/

**Comment by redhog** [comment]
That is definitely very very bad. I think however, that this code is broken anyway - the padHierarchy plugin seems to work server-side wise, but no styling seems to be there at all, and not client side js seems to work neither. So, basicly, this could just be removed until Michael Forrest (I think it was), who wrote the plugin, fixes the UI :)

**Comment by computercolin** [comment]
Cool, I would support that move. Should we send an email to the list for comments?

**Comment by redhog** [comment]
yes please :)
