### ISSUE TITLE
post (create pad) and read by email

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#181]
It would be great to be able to post emails to a given address, say post@my.etherpad.box, and have the content of the email turned into a pad with the given subject line.  Similarly it would be good to be able to subscribe to a given channel defined by some combination of tags, say "#etherpad #documentation" to be read by email.

**Comment by redhog** [comment]
The latter can be done by simply using any free rss-to-email gateway - all tag queries are available as RSS ( &format=rss in the URL).

Posting pads using email is an interesting possibility. It is also related to creating a generic json-rpc API for pad management.
