### ISSUE TITLE
pads that link to this pad busted in case of links that include spaces

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#182]
See http://piratepad.net/ep/search?linksto=wiki-links and compare http://piratepad.net/teh-broak (which includes the link [[wiki links]]

**Comment by redhog** [comment]
Interesting... Any idea of when this happens?

**Comment by holtzermann17** [comment]
My guess is that it is only because [[wiki links]] is actually a link to "wiki-links".  Search can find [[wiki-links]] no problem.  I think there may be a related issue that once a page is "found" it stays found even if the link goes away!  (check http://piratepad.net/teh-broak again).

**Comment by redhog** [comment]
Hm, that latter thing is obviously a security bug. Must be some error in how PAD_LINK_CACHE is handled...

As for "wiki link" being the same as "wiki-link", I wonder what really ends up in PAD_LINKS? Could you check?

This probably just needs a few extra string transformations in the db-writer hook
