### ISSUE TITLE
Clear chat

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#19]
Clear chat window, retaining the contents of the pad.

**Comment by sesam** [comment]
Is the use case that the user want's to "mark as read" for chat contents?

Etherpad so far makes all changes occur everywhere insta-simultaneously. It would be nice to stay with this principle when possible. Therefore, clearing the chat (making text invisible) might be unsuitable.

The simplest non-intrusive option is to fade chat contents via the window.onblur event, which means when you switch to another window (or tab) temporarily.

A more fancy option is to have a specific "Mark chat as read" feature, perhaps a button that would place a horizontal line at the bottom of the chat to mark you've already read to there. New incoming chat lines would then never let the chat window scroll past this horizontal line, and perhaps even light up/outline the chat area in bright colours to get your attention to go and read through the new chat messages.

**Comment by redhog** [comment]
I think the original poster intended a "erase chat history with not-suitable-for-public comments" on a pad prior to posting the link to said pad on say a public webforum or somesuch

**Comment by holtzermann17** [comment]
Marking as "Milestone 1.2" since after the Etherpad Foundation meeting of June 30, 2010, it seems that we want a "favourite feature-add" release after the 1.1 release, and "clear chat" was the best example anyone could come up with of a feature to add (at the time ;)).

**Comment by redhog** [comment]
This is related to issue #111 and has the same problems. Maybe move to 2.0?
