### ISSUE TITLE
Custom SMTP Mail Server

### ISSUE THREAD

**Issue by Dalek** [ether/pad#190]
Issue: Etherpad assumes localhost as smtp server.
Problem: Dynamic IP's are genrally blocked as mail servers
Possible Solution: Allow for a simple configuration of smtp mail servers with standard authentication.

Details: Currently, to allow for any other mail server outside of localhost, one must modify the pad/infrastructure/net.appjet.oui/config.scala 

from the defaults starting with the comment:

// email

To include the appropriate server info, and then recompile the project. This seems excessive, and despite the quick fix listed online regarding google email support, I have not yet found a way to make gmail work.

**Comment by JohnMcLear** [comment]
Email Configuration

Etherpad can send invite emails to other pads. To configure the email account these invites are sent from, you can pass in the SMTP server, username and password used by the server using the smtpServer, smtpUser, and smtpPass configuration options, respectively. Note that if your SMTP server does not require authentication, you may leave the smtpUser and smtpPass parameters unset.

Source: https://github.com/karteek/etherpad/blob/master/users-guide.md
