### ISSUE TITLE
Email invitation to edit a pad sends undefined as link URL

### ISSUE THREAD

**Issue by JohnMcLear** [ether/pad#191]
Bug since 1.1 when a user is invited via email to a pad the pad URL is undefined.

**Comment by JohnMcLear** [comment]
This is easily fixable by jumping into pad_body2.ejs and modifying the offending line of code.  The value is probably something like <%=padUrl%>.  Can anyone submit a fix for this please?

**Comment by nigelbabu** [comment]
I think it has something to do with the fact that the js that actually does the url replacement looks for #sharebox-url but sharebox-url is now a class and not ID.  What is the ideal fix?  Fixing the class to be an ID again or changing the JS?

**Comment by sesam** [comment]
Thanks, patch commited
