### ISSUE TITLE
/etc/init.d/etherpad etherpad 1.1

### ISSUE THREAD

**Issue by mstuder** [ether/pad#192]
The init-script /etc/init.d/etherpad does not work for etherpad 1.1 (Debian 64bit)
Best regards
Martin

PS: How is it possible to add labels to github issues?

**Comment by redhog** [comment]
Re labels: you have to be a team member, You're added now :)

**Comment by mstuder** [comment]
thx redhog! 

I changed now /etc/init.d/etherpad on my installation instead of 
start-stop-daemon --background --chdir $DAEMON_BASE --chuid etherpad:etherpad --start --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \   $DAEMON_ARGS \

I use:
$DAEMON >> /dev/null & echo $! > $PIDFILE &
