### ISSUE TITLE
etherpad.local.properties in debian package

### ISSUE THREAD

**Issue by kallies** [ether/pad#196]
I'm note sure if this config/documentation bug is in version 1.1 if you're doing the installation from scratch, but it was in 1.0.1 and is still in 1.1 after upgrading. Etherpad looks for the config file in /etc/etherpad.local.properties and the template is located in /etc/etherpad/etherpad.local.properties.tmpl. The configuration generated by dpkg is also located in /etc/etherpad/ and Etherpad doesn't care about it.

**Comment by sesam** [comment]
This might already be fixed -- can you check again against the latest source code version?

**Comment by vaurat** [comment]
not commited in deb package yet (v1.1), still seeing :
cfg_file=./etc/etherpad.local.properties
that is not existing.
as explained before in http://luke-x.blogspot.com/2011/06/etherpad-installation-on-debian.html
