### ISSUE TITLE
add support for more semantic structures, better long document authoring

### ISSUE THREAD

**Issue by bdarcus** [ether/pad#197]
Right now, etherpad has support for very basic semantic structures: paragraphs and lists. This makes it suitable for only very short documents. In order of my own priority, then, please add:
1. headings
2. blockquotes

This could then be easily built on over time by adding, for example, table of contents (drawing on headings), and styling support.

**Comment by juba** [comment]
+1 

Supporting some headings levels would be a great improvement for me too !

**Comment by xmbms** [comment]
I have done the heading levels support. If interest, you can visit http://www.fisherstory.com . Source code available at https://github.com/xmbms/pad

**Comment by bdarcus** [comment]
Awesome; thanks!

I will say, though, that I'm not at all a fan of adding the font and font-size menus. I think that's a step backwards.

**Comment by xmbms** [comment]
I also add a config file which locate in the root directory of richText plugins . you can disable/enable features in this file.
