### ISSUE TITLE
Popup that tells you you've been disconnected obscures the pad (and won't let you scroll it)

### ISSUE THREAD

**Issue by dreeves** [ether/pad#203]
When you get disconnected, the pop-up obscures part of the text of the pad and you can't scroll.  That's bad because sometimes you'll bring up a pad for reference and then unplug from the network.  In the original version you could still view the pad when offline.  It wouldn't let you type in it so there was no danger of not realizing you weren't connected.

**Comment by itguy51** [comment]
While connected, you should be able to bring up the Read-Only version of the pad, which does not require any connectivity, and should not display a disconnected message.

**Comment by dreeves** [comment]
Agreed. But I think that's orthogonal. If you hadn't happened to have brought up the read-only version then disconnecting should not cause it to become unreadable.
