### ISSUE TITLE
Remember state of full screen

### ISSUE THREAD

**Issue by dreeves** [ether/pad#204]
In the original etherpad release, if you made a pad full screen it would remember this when you reloaded the page.  In the 1.1 release it always reverts to not full screen, which is a bit of an annoyance.

**Comment by nigelbabu** [comment]
I think this could be similar to Issue #199 which is fixed in master.

**Comment by sesam** [comment]
The remembered settings work only sometimes. It seems there could be a timing issue (or "race condition"?) that makes this sometimes work, sometimes not.

dreeves, do you see the full screen problem repeatedly also if you reload the page? With and without preserving cache when reloading?

**Comment by dreeves** [comment]
I believe the answer is yes to both. I know that etherpad 1.0 doesn't have this problem.
