### ISSUE TITLE
Wrong path in Debian package

### ISSUE THREAD

**Issue by jonasob** [ether/pad#205]
The Debian package for Etherpad has in its /etc/init.d/etherpad the DAEMON_BASE /usr/local/etherpad whereas the package contains etherpad in /usr/share/etherpad. A simple replace fixes that and makes etherpad start :-)

We discovered this while installing http://pad.ffkp.se/

**Comment by brother** [comment]
duplicate of 195, please close this one.

**Comment by sesam** [comment]
Duplicate of #195
