### ISSUE TITLE
etherpad 1.1 export error

### ISSUE THREAD

**Issue by conloos** [ether/pad#207]
Hi,

i have successfully installed a etherpad1.1. Most parts seems to work. But the export to Word, PDF and OpenOffice didnt work. I get this message:

```
Error: Conversion timed out. Please try again later.
```

My setup:
OS: Ubuntu Server 10.10 (as a VM)
Etherpad: 1.1

Does have anybody this behavior.
I didn't have any idea to continue.

Con

**Comment by JohnMcLear** [comment]
It sounds like openoffice isn't installed

try apt-get install open-office-headless

**Comment by conloos** [comment]
Thanks the OO was two times started. Seems that there is a bug in the init- Script and restart didnt work.
