### ISSUE TITLE
Error: An unknown failure occurred. (#3)

### ISSUE THREAD

**Issue by conloos** [ether/pad#208]
Hi,

i have a error ( Error: An unknown failure occurred. (#3) ) by trying to export a pad to doc, pdf or odt.
The OO is started:

```
#ps aux | grep openoffice
etherpad   845  8.1  8.6 409968 43436 ?        Sl   21:43   0:30  usr/lib/openoffice/program/soffice.bin -headless -nofirststartwizard -accept=socket,host=localhost,port=8100;urp;StarOffice.Service -splash-pipe=5
```

The logs didnt show a reason ....
Any Idea.

OS: Ubuntu 10.10 (KVM - Guest)
Etherpad: 1.1

Thanks Con

**Comment by Erode** [comment]
Is it started only once ?
Should try to update to version : 1:3.1.1-5ubuntu1.3 or higher

**Comment by Erode** [comment]
Well,

I was on an older Ubuntu server, as the version a gave is pointing out.
In the same circumstances, Ubuntu 10.10, Etherpad 1.1, OOo  1:3.2.0-7ubuntu4.2 it's not working. And, the puzzeliest thing is that effectively no logs are telling which exception it is.

Should be the classical : URL seems to be Unsupported in loadComponentFromURL
As it's the unknown #3

**Comment by Erode** [comment]
So, we just can't rely on the dependencies induced by the installation of the Ubuntu package to have OOo conversions working.
On my server I installed the complete version of OOo via the package « openoffice.org » (of the same version than already reported) and after having killed the running soffice then etherpad instances and a wait for the watche-dog to figure it out, it was working :)
