### ISSUE TITLE
Depend on openjdk-6-jdk rather than sun-java6-jdk

### ISSUE THREAD

**Issue by doherty** [ether/pad#210]
We should attempt to use openjdk rather than Sun's non-free jdk if possible.

**Comment by JohnMcLear** [comment]
We already have.

**Comment by doherty** [comment]
Hm. When using git-buildpackage to create a .deb, I get `dpkg-checkbuilddeps: Unmet build dependencies: sun-java6-jdk`

**Comment by JohnMcLear** [comment]
Ugh.  The deb has an incorrect dep by the looks of things
