### ISSUE TITLE
Chrome & Safari Connection Error

### ISSUE THREAD

**Issue by nivoc** [ether/pad#211]
I've just installed Etherpad on Debian. But there is an Issue with Chorme&Safari (I guess Webkit).

I'm unable to use Etherpad. 
1) If I open it - I get a welcome-page with a big button 'create a new pad'
2) Click the blue 'Create new pad' button.
3) The Etherpad UI loads, but with a dialogue which says 'Yes, create the pad'. 
4) Click that button, and it just reloads the page.

In Fireworks - everything works fine. If I create a Pad in Firefox and try to use it in Safari, Safari will load the Pad but stops working than with a "connection lost"-Error dialog

:(((

**Comment by JohnMcLear** [comment]
There have been a few bug fixes, I haven't actually seen this problem but a few people have reported it.  To be honest it doesn't make sense that it exists..

Either way take a look here:  http://github.com/ether/pad/network

If you can show me it live that might help :)

**Comment by nivoc** [comment]
unfortunately my instance has no direct internet connection but JonA has the same issue and told me he will post a link

**Comment by jonatkinson** [comment]
I'm experiencing this issue too. I seem to have the same issue as the OP, I can't create a new pad in Safari or Chrome, but I can with Firefox.

I've got a public instance of Etherpad running here, which exhibits these problems: http://89.16.165.102:9000/

**Comment by JohnMcLear** [comment]
Do you have any superdomains listed?  If so, what are they and I will create a local host entry.  I would strongly advise against testing etherpad by IP.  The hostname is required due to the nature of the service.

**Comment by jonatkinson** [comment]
I'm not sure what you mean by 'superdomain' - could you clarify?

**Comment by JohnMcLear** [comment]
In your etherpad.local.properties there is a line, topDomains..  What is your value?

You will of been asked your domain during apt-get install setup.

**Comment by JohnMcLear** [comment]
In your etherpad.local.properties there is a line, topDomains..  What is your value?

You will of been asked your domain during apt-get install setup.

**Comment by nivoc** [comment]
for me it's "topdomains = 10.0.0.4"

**Comment by jonatkinson** [comment]
Ah, sure.

During install, I was asked for a domain, so I used office.testled.com (which points to that IP address), however I then had a problem where Etherpad would try to redirect me to http://false/

I changed the topdomains line to contain the server IP address (based on something I read in the Google Group, I think). It's now this:

topdomains = 89.16.165.102,localhost,localhost.localdomain

**Comment by JohnMcLear** [comment]
89.16.165.102 is not a domain.  Add a domain IE etherpadtest.com then add your own local DNS records.

**Comment by nivoc** [comment]
Yes - thanks - It works for me if i use topdomains = etherpad.com and enter into my etc/hosts file 10.0.0.4 etherpad.com

**Comment by nivoc** [comment]
is it working for you too jonatkinson? If yes - I'll close this issue.
