### ISSUE TITLE
ability to configure base URL with nonstandard port and path

### ISSUE THREAD

**Issue by edgimar** [ether/pad#213]
I would like to use Apache's ProxyPass directive to make etherpad accessible at the following URL:

https://blah.mydomain.tld:12345/etherpad

"blah" is shared by several different web-applications, which use different paths (e.g. /etherpad or /myapp...).

There is no clear and easy way to configure etherpad to generate all of its URLs to have the form https://blah.mydomain.tld:12345/etherpad/path/to/resource

This would be a very important feature for systems where only one FQDN is available (i.e. no other subdomains) for whatever reason.

**Comment by redhog** [comment]
To configure etherpad to work through Apache is easy - but to get it to work on a subdirectory path (/etherpad or /somename) isn't as easy. Etherpad unfourtunately does not have a URL reverser like Django, so all links are just normal <a href>:s. So if you just moved it, you'd most likely end up with broken links all over the place.

Uggly hack:
However, as long as you can stand there being /ep and /fewotherthings, you can sort of rather easily move the pads themselves to /whatever using etherpad/src/main.js

This is clearly something we should work on to make possible!

**Comment by itguy51** [comment]
This would be really useful. I tried hacking it by modifying all of the URL handlers and adding a prefix to them (adding 
'prefix + ' to the beginning of each one, and declaring 'var prefix = "/etherpad"') but it didn't work. This tells me that the system parses URLs in another area other than handlePath()

**Comment by redhog** [comment]
In what way did it not work? I guess the problem is that all URLs _generated_ by Etherpad (for links etc) are still against /, not /whatever... But fixing this would definitely be a very very welcome patch, as would supporting team pads without subdomains...

**Comment by itguy51** [comment]
here's my hack, 

var prefix = "/ep";

  commonDispatcher.addLocations(plugins.callHook('handlePath'));

  commonDispatcher.addLocations([
    [prefix + '/favicon.ico', forward(static_control)],
    [prefix + '/robots.txt', forward(static_control)],
    [prefix + '/crossdomain.xml', forward(static_control)],
    [PrefixMatcher(prefix + '/static/'), forward(static_control)],
    [PrefixMatcher(prefix + '/ep/pad/'), forward(pad_control)],
    [PrefixMatcher(prefix + '/ep/script/'), forward(scriptcontrol)],
    [prefix + /^\/([^\/]+)$/, pad_control.render_pad],
    [DirMatcher(prefix + '/ep/unit-tests/'), forward(testcontrol)],
    [DirMatcher(prefix + '/ep/pne-manual/'), forward(pne_manual_control)],
    [DirMatcher(prefix + '/ep/pro-help/'), forward(pro_help_control)]
  ]);

  // these paths are main site only
  var mainsiteDispatcher = new Dispatcher();
  mainsiteDispatcher.addLocations([
    [prefix + '/', maincontrol.render_main],
    [DirMatcher(prefix + '/ep/beta-account/'), forward(pro_beta_control)],
    [DirMatcher(prefix + '/ep/pro-signup/'), forward(pro_signup_control)],
    [DirMatcher(prefix + '/ep/about/'), forward(aboutcontrol)],
    [DirMatcher(prefix + '/ep/admin/'), forward(admincontrol)],
    [DirMatcher(prefix + '/ep/blog/posts/'), blogcontrol.render_post],
    [DirMatcher(prefix + '/ep/blog/'), forward(blogcontrol)],
    [DirMatcher(prefix + '/ep/connection-diagnostics/'), forward(connection_diagnostics_control)],
    [DirMatcher(prefix + '/ep/loadtest/'), forward(loadtestcontrol)],
    [DirMatcher(prefix + '/ep/pro-account/'), forward(global_pro_account_control)],
    [prefix + /^\/ep\/pad\/history\/(\w+)\/(.*)$/, historycontrol.render_history],
    [PrefixMatcher(prefix + '/ep/pad/slider/'), pad_control.render_slider],
    [DirMatcher(prefix + '/ep/store/'), forward(storecontrol)],
    [PrefixMatcher(prefix + '/ep/'), forward(maincontrol)]
  ]);

**Comment by itguy51** [comment]
I never expected it to work, it was just an experiment, and it behaves the exact same way as it did before i did that.

**Comment by itguy51** [comment]
Does anyone know exactly where the URLs are generated? I don't want to have to dig through all this code to find it, I will, but it would probably take longer that way. My logic would be, a line in the etherpad .properties file, there would be a line like 'base = /etherpad'

**Comment by redhog** [comment]
All over the place unfourtunately. Appjet does not have a nifty "reverse URL" function like Django :( So there are lots of hardcoded links in templates and the like...

If someone would feel like making a reverse matcher that'd be great. Otherwise I guess a simple appjet.config.baseUrl + "/foo/bar" would work...

**Comment by itguy51** [comment]
Now, is there a way to run the server without having to build it every time I write a line of code? or is that kinda required...
I want to work on this, but building it is a pain, because if I have to rebuild it everytime I experiment, it seems inefficient

**Comment by itguy51** [comment]
Well, A plus is that the majority of HTML rendering, is in helpers.js, so getting it to run on a directory path is doable, but getting it to understand those, is the bigger difficulty.

**Comment by itguy51** [comment]
How do I access the appjet.config in one of the SSJS files? I see it done like appjet.config['key']; but it's not working, Do I have to import something?
