### ISSUE TITLE
Etherpad 1.1 and IE7 : 1 problem solved, 1 remaining (pad's height too short)

### ISSUE THREAD

**Issue by gabrielcossette** [ether/pad#215]
Hi,

Etherpad 1.1 had a major problem with IE 7 browser: it wouldn't want to load at all.

I fixed it with this small patch

In /usr/share/etherpad/etherpad/src/static/js/ace.js there is this line:

var AZ={clearauthorship:function(i){if((!(A.selStart&&A.selEnd))||P()){if(i){i();\n}else{AR(0,A.alltext.length,[["author",""]]);}}else{Az("author","");}},}

Well, turns out IE7 doesn't like the comma at the end even though IE8 just ignore it.

If I just remove it like this:

var AZ={clearauthorship:function(i){if((!(A.selStart&&A.selEnd))||P()){if(i){i();\n}else{AR(0,A.alltext.length,[["author",""]]);}}else{Az("author","");}}}

IE 7 loads!

However, here's the remaining problem, the pad's height is only 8 lines before it scrolls down.

Can someone look at this? We are close to support IE7 fine in Etherpad 1.1 ;)

P.S.: I don't actually run IE but some of my clients do ;)

**Comment by gabrielcossette** [comment]
Hi everyone,

Someone on the mailing list (groa) just posted a fix for this problem:

In /usr/share/etherpad/etherpad/src/themes/default/templates/html.ejs

Add this line (after  for example):



With that small change, it's at least acceptable for IE7 users.

**Comment by tomcarlson** [comment]
The above works ... but not for the time-slider view.  To fix that, you need another style defined as below. 

```
  \usr\share\etherpad\etherpad\src\themes\default\templates\html.ejs

  <!-- CSS -->
  <!--[if IE]> 
      <style type="text/css"> 
        #editorcontainerbox { height:92%; } 
        #padpage{ height:92%; } 
      </style> 
    <![endif]--> 
```
