### ISSUE TITLE
remove @etherpad.com

### ISSUE THREAD

**Issue by sesam** [ether/pad#218]
At least in  etherpad/src/etherpad/pro/pro_accounts.js  is there a line
 email: "support@etherpad.com"
which probably should be replaced with the pad admin account, perhaps findable in the properties -file.

**Comment by laughinghan** [comment]
I believe pro accounts are disabled in the open source EtherPad?

**Comment by sesam** [comment]
You can enable pro with configuration, and anyway that's not a reason to keep incorrect emails hardcoded.
We probably don't want an open source project to have stuff in it that sends off automated emails into the googleplex via sales@etherpad.com and blackhole@appjet.com

Apart from etherpad/src/etherpad/pro/pro_accounts.js there's also at least these:

Unknown priority:
etherpad/src/etherpad/control/aboutcontrol.js

Low-priority:
etherpad/src/etherpad/billing/team_billing.js

I can do an exhaustive file grep if that helps with prioritizing this issue.
This project actually needs a bunch of configurables which for now should go in the .properties file. Or we could just make these emails just default to postmaster@SERVER_DOMAIN_NAME but that would risk problems especially with the mails intended for blackhole.
So most probably all this emailing should be configurable and switched off by default?

**Comment by sesam** [comment]
Higher priority:
control/pad/pad_control.js
control/global_pro_account_control.js

Further low priority:
store/eepnet_trial.js
store/eepnet_checkout.js
control/store/eepnet_checkout_control.js
control/pad/pad_control.js

And there are more hardcoded emails than I ever imagined. The less frequently used ones / only in text blocks are feedback@etherpad.com support@etherpad.com urgent@etherpad.com
