### ISSUE TITLE
Move from c3p0 to Apache Commons DBCP?

### ISSUE THREAD

**Issue by overholt** [ether/pad#219]
Hi,

Some of us are trying to get Etherpad packaged for Fedora.  One of the dependencies that we're having trouble with is c3p0.  It looks like c3p0 only builds against Java 1.5 and we would like to use OpenJDK which is 1.6.  I tried building c3p0 with gcj (which has GNU Classpath which is at 1.5) but ran into some issues with their javax.sql compatibility.

Is there any chance of etherpad moving to use Apache Commons DBCP instead of c3p0?

http://commons.apache.org/dbcp/

Thanks,

Andrew Overholt

**Comment by sesam** [comment]
c3p0 is LPGL, latest release was in 2007, so might anyways be dead.
DBCP is in Debian and Ubuntu  http://packages.ubuntu.com/source/lucid/libs/libcommons-dbcp-java

So, patches welcome... :)
Perhaps http://community.jboss.org/wiki/HowToconfiguretheC3P0connectionpool is useful in understanding the existing c3p0 code.

**Comment by overholt** [comment]
So you're saying you'd like help porting to DBCP?  I'll see if I can drum up some help :)  DBCP is in Fedora, too, FWIW.

**Comment by cjb** [comment]
Even if you get it to compile on OpenJDK (I thought I'd done so in the past..), etherpad doesn't run under OpenJDK; it crashes immediately.  So, heads up on that too.

**Comment by ijuma** [comment]
Any more details regarding the crash? For instance, what was the OpenJDK version and was it a JVM crash or some library issue?

**Comment by cjb** [comment]
Sorry, I have no details.  It's easy to reproduce by compiling etherpad under Sun Java and then trying to start it using OpenJDK.

Our old FAQ entries/mailing list posts mentioned this and might well have included a paste of the error message.

**Comment by sesam** [comment]
It seems that c3p0 is imported in one single place in infrastructure/net.appjet.ajstdlib/sqlbase.scala:  import com.mchange.v2.c3p0._;
I'll leave this to scala-literate people to judge if it's easy to replace in there or not.

**Comment by pedalpoweredsoftware** [comment]
Here's a good discussion of c3p0, DBCP, and the alternatives:
http://stackoverflow.com/questions/520585/connection-pooling-options-with-jdbc-dbcp-vs-c3p0

**Comment by sesam** [comment]
@pedalpoweredsoftware Thanks, that makes it clear that DBCP is still to be avoided as the plague. BoneCP from http://jolbox.com/ seems to be a drop-in replacement for c3p0 and also with much better performance: http://jolbox.com/dynamic-benchmark.html
Who's up to testing BoneCP asap? Latest version 0.7 announcement:  http://forum.jolbox.com/viewtopic.php?f=3&t=151
Also in 0.7 release notes: Changed license to Apache v2.0 -- so should be painless for apache-supporters to use this one :) Packaging though?

**Comment by sesam** [comment]
Also, choosing BoneCP means we need another 2 packages:
- SLF4J (MIT license & widely packaged) http://www.slf4j.org/
- a Collections lib which is found in http://code.google.com/p/google-collections/ or since it seems to need packaging, better go right at the newer superset library http://code.google.com/p/guava-libraries/  (Apache2.0 license)
