### ISSUE TITLE
better admin control, esp. for pad deletion

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#22]
We need better ways to clear offensive pads quickly (this will be true even when there is login/authentication).

**Comment by sesam** [comment]
Code to remove a pad completely (untested) at http://dtherpad.com/nuke

**Comment by JohnMcLear** [comment]
I'm voting to put this into 1.1

**Comment by redhog** [comment]
Would this be from the management console?

**Comment by JohnMcLear** [comment]
Yes.  But also admin access to individual management consoles would be ideal.

**Comment by elijh** [comment]
+1. I think pad deletion is very important.

**Comment by redhog** [comment]
redhog/pad now contains a plugin that does this (from the admin console)

**Comment by elijh** [comment]
wow, that is great!

**Comment by redhog** [comment]
Cool. I'm not sure if this deletes every trace in the DB thou. But it sure makes it vanish from the users' perspective. Anyone wanna have a go at verifying if there are traces and if so how to delete them? I'd like this to be useful even in the context of trade secrets, confidential material etc.
