### ISSUE TITLE
make debconf ask for mysql information

### ISSUE THREAD

**Issue by brother** [ether/pad#221]
while using the debian package of etherpad to install with it does not offer the possibility use other hosts than localhost and so on. even if the debconf script has support for parts of that (it only uses a default of localhost:3306.

something like this can be used to add the necessary questions and backbone code to the setup. haven't tested it at all, feel free to use it as you like. license wise it will fit your needs.

brother ~/tmp/etherpad (master)$ cat debconf.patch 
diff --git a/control/postinst b/control/postinst
index 36d3aa9..d106915 100755
--- a/control/postinst
+++ b/control/postinst
@@ -39,6 +39,12 @@ db_get "etherpad/admin_password"
 db_admin_password="$RET"
 db_get "etherpad/topdomains"
 db_topdomains="$RET"
+db_get "etherpad/mysql_etherpad_user"
+dbc_dbuser="$RET"
+db_get "etherpad/mysql_etherpad_password"
+dbc_dbpass="$RET"
+db_get "etherpad/mysql_etherpad_host"
+dbc_dbserver="$RET"

 . /etc/dbconfig-common/etherpad.conf

diff --git a/control/templates b/control/templates
index 91c9cfd..9eb2610 100644
--- a/control/templates
+++ b/control/templates
@@ -21,3 +21,27 @@ Description: Fully qualified domain name of the site:
 Description-fi.UTF-8: Etherpad-palvelimen osoite (esimerkiksi example.com):
  Järjestelmän tulee tietää Etherpad-palvelun täydellinen julkinen domain-nimi. Tämä voi olla eri kuin sen tietokoneen domain-nimi, johon palvelu asennetaan (esimerkiksi kun käytetään porttien uudelleenohjausta tai reverse proxy -määrityksiä). Huomaa, että jos syötät tässä "example.com", niin palvelu on oletuksena nähtävillä osoitteessa "http://example.com:9000".

+Template: etherpad/mysql_etherpad_user
+Type: string
+Default: etherpad
+Description: MySQL user for Etherpad:
- Please specify the MySQL user Etherpad will use to store and read
- data from the MySQL database.
- The default username is "etherpad".
  +
  +Template: etherpad/mysql_etherpad_password
  +Type: password
  +Default: password
  +Description: MySQL user password for the Etherpad database:
- Please specify the MySQL user password Etherpad will use to store and
- read data from the MySQL database.
- The default password is "password" (THIS IS NOT SAFE). The password
- will be stored in clear text in the cofiguration file.
  +
  +Template: etherpad/mysql_etherpad_host
  +Type: string
  +Default: localhost
  +Description: MySQL server hostname for the Etherpad database:
- Please specify the MySQL server hostname where the Etherpad database
- will be stored.
- The default is "localhost".

**Comment by redhog** [comment]
How does this (not) interact with db-config-common, which we are currently using? Is there a way to offer both options (setting up a local mysql automatically, and allowing for a remote manually configured one)?

**Comment by brother** [comment]
github really destoyred that paste =)

I don't know enough debconf to work the two ways out.
Maybe it's not a good idea tp let people choose the hostname, username, password org database via input dialogs for some reason. If that's not the case then it's just a simple matter of using the information they provide, if they use localhost or a remote host as target system. How db-config-common works I have _no_ clue to at all. sounds like a loclahost-only-thngie. in that case I would have inserted a question for local or remote server and based on that answer provided the track needed. it's just a matter of get local question and if (( $RET = 1 )); then sub_config_local(); else; sub_config_remote(); fi. The config script is far from horrible to read.

maybe these files are available in this very repo. haven't really looked into that possibility, I extracted it from the deb to see what it did =)
