### ISSUE TITLE
both Read-Only and Timeslider features broken (which code/version?)

### ISSUE THREAD

**Issue by Erode** [ether/pad#227]
With an Etherpad from Etherpad Foundation, installed from .deb package, I get :

404 not found: /ep/pad/view/ewYN8SCdCV/rev.12

When clicking on ether : 
- Link to this version
- Link read-only

No exception generated.

Any hint on fixing this ? It was working with previous versions.

**Comment by sesam** [comment]
You forgot to mention where you get this error message. If it is about the small box in the lower right, that's quite normal I'm afraid and you have to create your own intro-page either as a pad or as a static or any other page, then go and change the configuration to point to your own "welcome" box URL.

**Comment by Erode** [comment]
Thanks for your reply :)

I'm get this error in full page when clicking on any of the two links mentionned before, in any pad « time-slider » on my server.

**Comment by sesam** [comment]
It could possibly be a known & fixed problem (I'm thinking of https://github.com/ether/pad/commit/6ca74a5d6eea1176cd3378abe0f87fa1449d3a7d )

So if you feel confident, perhaps try to get the latest version from github https://github.com/ether/pad/tarball/master  and see if that fixes your problem?

**Comment by Erode** [comment]
I read this issue but the provided fix is not in the field. The URL on which the time-slider-links are correct (on the same schema than on working previous-version pads), just, nothing try to answer it in my 1.1 stock version.

framapad.org/ep/pad/view/ewYN8SCdCV/rev.12

(I did hide the implied links on the time-slider page, but you have it here)

**Comment by sesam** [comment]
Oh, I just re-tried with _updated_ latest trunk and it works for me. Erode, could you also try again?

**Comment by sesam** [comment]
Closing due to no reaction from Original Poster. If you get around to trying code downloaded from github.com/ether/pad and still have issues, then please start a new Issue instead.
