### ISSUE TITLE
Easy way to deactivate public pads

### ISSUE THREAD

**Issue by LarsFronius** [ether/pad#228]
Hi,

We want to use etherpad for our workgroups in the institute to work collaborative and secure on documents. The workgroup and security-aspect leads me to the point, that we don't need public pads. So: How do I "easily" deactivate this functionality?

**Comment by sesam** [comment]
etherpad was never built for this use case. You'd need to put a proxying webserver in front of etherpad, or make a firewall rule to to the blocking lower down on the IP level. Support requests are very welcome in the mailing list otherwise :). Try etherpad.org on how to find the support channels.
