### ISSUE TITLE
Shibboleth Authentication

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#23]
It would be nice to control user access at the "pad" level as well as at the "bloc" level.

**Comment by JohnMcLear** [comment]
I'm working with niels.vandijk@surfnet.nl & mark@schoolemail.co.uk to resolve this.

**Comment by JohnMcLear** [comment]
PS We are looking at creating a web facing API to allow just in time user account creation/provision.

**Comment by elijh** [comment]
johnyma22, that sounds great! any progress?
