### ISSUE TITLE
Missing dependencies/recommends in Debian package

### ISSUE THREAD

**Issue by aog2000a** [ether/pad#236]
For getting the OpenOffice converter to work with Debian package v1.1, not only the python-uno package is required but also 
        openoffice.org-headless
and
        openoffice.org-java-common
So all 3 packages should be entered as Recommends:.
Thanks.

**Comment by elrik** [comment]
openoffice.org-headless is a virtual package. Functionality is provided by openoffice.org-core package for Ubuntu after Hardy and for Debian since Lenny. So we could enter these 3 packages python-uno, openoffice.org-java-common and openoffice.org-core as recommends.
