### ISSUE TITLE
Bug with german umlauts

### ISSUE THREAD

**Issue by LarsFronius** [ether/pad#237]
I do have a bug when using umlauts in the pro panel.
For example if I am admin of a Pro-Site and Add a new account, which Full name should be something with an ü like Müller, which is a quiet often name in germany, it stores it as a &#252; sign. Which is not so nice.

I have heard of the same issue when using copy & paste from local word documents to a pad. But I can't confirm this. So I think this was fixed some time ago?!

**Comment by PDWE** [comment]
Same for me.
 ö is displayed as "& # 2 4 6 ;" ( without the spaces ;-) ) in the accounts list and connected useres list.
But in the pad, it is fine and displyed as ö.

Cheers, PDWE
