### ISSUE TITLE
Lines below line 1882 do not show in editor

### ISSUE THREAD

**Issue by kanadetachibana** [ether/pad#239]
Any lines below line 1882 do not show correctly in pads that exceed that number of lines. Content is still added correctly, and shows when highlighted. This bug is always reproducible.

Screenshot: http://puu.sh/1gFp

**Comment by sesam** [comment]
Which webbrowser make and version are you using?
The original developers of etherpad concluded that browsers at that time could not handle really long documents, due ot a builtin limit of the browser's contentEditable feature.

**Comment by kanadetachibana** [comment]
I mainly use Chrome 10.0, but it seems the bug also occurs in Firefox 3.6.

**Comment by Blazewardog** [comment]
Similar behavior in Firefox 4.0 and Chrome 11 on Windows

**Comment by Yuuji** [comment]
I commit a fix for it and opened a pull request

**Comment by JohnMcLear** [comment]
Needs fully testing in all browsers
