### ISSUE TITLE
beeps/flashing when pad is edited

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#24]
Enable attention-getting beeps or flashing to indicate when a Pad is being edited (similar to the behavior of GTalk etc.).

**Comment by sesam** [comment]
Principles:
- Effective (=disturbing) effects should be opt-in.
- Visual mark with bright colours. No blinking please.
- Sound brings issues with user volume settings, muting/unmuting (while the user watches a movie in fullscreen). Or not mute, if the pad happens to be Very Important. But, no sound please.

Use cases:
- use pad as chat-room => mark or flash a border around chat-box/edit area
- long-running editing. You keep the page open for hours and want to know if anything new has happened. (n.b. this would also need an option to auto-reconnect to the sync server) => have a timestamp for when last edit happened, i.e. "X days ago" and this goes bold/big/colourful whenever it changes, then fades back into its regular self when you hoover the mouse over that timestamp (and also if you click anything or type any key anywhere on the pad page).

**Comment by jaxyeh** [comment]
Sometime user did not realized someone else is trying to communicate via chat sidebar. Also, there should be visual indicator for new incoming chat message.
