### ISSUE TITLE
Deletion of password portected pads

### ISSUE THREAD

**Issue by Erode** [ether/pad#244]
Currently, you don't need the password of a pad (protected-by-single-password) to delete it.

I think that it should be prompted before deletion by a regular user, and kept as it is for deletion by an admin.

**Comment by rajkumarbss** [comment]
I am using 1.1 etherpad.org source code  and experiencing same issue. In pro a/c, any user can delete any pad including password protected pad. It will be great if only pad owner or admin able to delete pad. 

One more thing, is it possible to have available pads list are view-able only by shared user/pad owner/admin.
