### ISSUE TITLE
option for automatic new pad on connection

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#247]
This is another enhancement for users of embedded etherpads: instead of embedding a single pad, embed a link to a URI that spawns a new etherpad whenever a new connection is initiated.  The name of the pad should be available for quick copy/paste, facilitating re-use.

**Comment by sesam** [comment]
So, something based on http://YOURDOMAIN/ep/pad/newpad and adding parameters to make it embedded as opposed to the default "standalone" pad GUI?

(What if the usual embedding-parameters already work?)

**Comment by holtzermann17** [comment]
The idea here is that _one_ URI will work all the time (and won't redirect the client to a new page when a new pad is created).
