### ISSUE TITLE
Ubuntu repo install bad DAEMON_BASE path

### ISSUE THREAD

**Issue by cdavid** [ether/pad#249]
When installing from the repos, the daemon cannot be started using the "/etc/init.d/etherpad" incantation.

This is because the path DAEMON_BASE in etherpad.init points to DAEMON_BASE="/usr/local/etherpad" while it should point to /usr/share/etherpad.

**Comment by LudwigTirazona** [comment]
I installed the package on Debian Lenny, too. I spent a lot of time trying to figure out what was wrong, Turns out this was the problem. :)
