### ISSUE TITLE
'ethermacs'

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#25]
I can only imagine that (a) various forms of code highlighting; (b) inputting e.g. Chinese (c) ...

... is going to be an issue.  Wouldn't it be nice if we could just reuse the code from Emacs that does this? :)

**Comment by laughinghan** [comment]
If we can just write an "Ethermacs Lisp" interpreter...

**Comment by petteyg** [comment]
Ethervim is a much nicer sounding name :)
