### ISSUE TITLE
Clear authorship (on entire document) doesn't work on Firefox 4

### ISSUE THREAD

**Issue by jonespm** [ether/pad#255]
In Firefox 4, when clicking on the "Clear Authorship" button without anything selected and clicking OK on the dialog box nothing happens. In the firebug console the error **D is null** appears. Tested on most recent commit.

**Comment by sesam** [comment]
This is most likely by-design, to make it harder to remove authorship colors of the whole document by mistake.
It could be better to allow to switch on and off the authorship colors.

**Comment by jonespm** [comment]
Well, the button works in Chrome, Safari and Firefox 3.6.13, so I don't think it was by-design. ;)
