### ISSUE TITLE
soffice deamon goes mad

### ISSUE THREAD

**Issue by flowma** [ether/pad#257]
On debian squeeze with etherpad 1.1 installed through apt.etherpad.org the DocumentConverter.py deamon puts load on the CPU and makes a GREAT amount of DNS requests.

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND     
 1208 etherpad  20   0  189m  34m  29m S 56.7  3.4   2249:35 soffice.bin 
```

Any hints?

**Comment by tosage** [comment]
I have the same issue on an etherpad installation on ubuntu server :/
Anybody haven't an idea of this bug ?

Thanks for reply ;)

**Comment by mrj10** [comment]
Same issue here, Ubuntu 10.10 server.  Tons of DNS request for localhost.(none).bla.bla.  Similar to what was reported here http://groups.google.com/group/etherpad-open-source-discuss/browse_thread/thread/87359428b4ea2761 and here http://p2pu.lighthouseapp.com/projects/71983/tickets/7-monitor-the-soffice-that-etherpad-starts

**Comment by dennisse** [comment]
Having the same issues here on a debian 6.0.4 server.
Etherpad causes thousands of lookups each second, and pulls an entire cpu thread. It also causes bind to use an entire thread because of all the lookups.

Any help would be greatly appreciated.

**Comment by sirkitree** [comment]
same issue using the latest debian package

**Comment by dennisse** [comment]
easy fix: switch to the newer etherpad lite.
https://github.com/Pita/etherpad-lite

**Comment by sirkitree** [comment]
I appreciate everyone is pushing the new version, however I can't get my old pads converted so I'm forced to use this one right now.

**Comment by Pita** [comment]
@sirkitree see https://github.com/Pita/etherpad-lite/wiki/How-to-migrate-the-database-from-Etherpad-to-Etherpad-Lite
