### ISSUE TITLE
importing file to pirate pad

### ISSUE THREAD

**Issue by mugeor** [ether/pad#258]
while trying to import a .png file it says:
Import failed: Unsupported file type: png. Etherpad can only import txt, html, rtf, doc, and docx files. 

but on the other hand, while trying to import a .docx file it says:
Import failed: EtherPad is not configured to import or export formats other than txt and html. Please contact your system administrator for details.

**Comment by JohnMcLear** [comment]
Try PrimaryPad, FYI issues specific to site hosting should be raised w/ the site, not here.

**Comment by redhog** [comment]
I think his issue is that the two error messages kind of contradict each other. Not that that's a huge problem anyway...

**Comment by sesam** [comment]
Both error messages were from etherpad/src/etherpad/importexport/importexport.js
and I've solved this in bc6c781de5628ce9f4655b4367fb17451de4a8b8, so may this issue rest in peace.
