### ISSUE TITLE
RFE: Please add kerberos authentication support

### ISSUE THREAD

**Issue by fabbione** [ether/pad#259]
It would be very handy, in many centralized auth environment, to be able to support a "one password" system via kerberos.

**Comment by dpasqualin** [comment]
I agree :)

**Comment by JohnMcLear** [comment]
This software is no longer supported

Perhaps you meant to comment on the ether/etherpad-lite repo?

**Comment by dpasqualin** [comment]
Absolutely..
Thanks.
