### ISSUE TITLE
use Emacs as a client

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#26]
Hey, if we can use Emacs as a client, we won't need reimplement a lot of the things it does so nicely.  Cf. http://groups.google.com/group/wave-client-for-emacs-discuss/browse_thread/thread/3113b6b81fd209ee

**Comment by redhog** [comment]
This is just a question of implementing something that accepts and sends changeset streams.  Have fun. It's a lot of code :)

**Comment by holtzermann17** [comment]
A step we've discussed: Let's draw a line around the protocol-managing part
of the client in the Etherpad code, and separate it from everything else.

**Comment by holtzermann17** [comment]
Marking this as high priority because I think it's cool and I want to work on it (sometime next month or thereabouts).

**Comment by canercandan** [comment]
Nice, I am also enthusiast for an integration of the etherpad features in emacs. What is going on here then ?

**Comment by glogiotatidis** [comment]
I'm also really interested. Are there any status updates?

**Comment by rakete** [comment]
I would like that too, did anyone attempt to make it work?

**Comment by holtzermann17** [comment]
have some patience

**Comment by rakete** [comment]
I am like the zen master, I just wanted to signal to you guys that I am interested in such a feature.

**Comment by dku** [comment]
+1
