### ISSUE TITLE
Export as plain text should be in reST/Markdown/Textile

### ISSUE THREAD

**Issue by timClicks** [ether/pad#266]
We are using a fairly old version of Etherpad at okfnpad.org, so my apologies if this issue has already been implemented.

When exporting a document as plain text, bolded lines are not given any prominence. This could be improved by supporting one of the several plain text formats which are intended to add readability.

**Comment by ilpssun** [comment]
That would be a very nice feature, probably not hard to implement.  Especially handy with respect to the buggy DOC/ODT export (→ issue #212).

**Comment by jacobSingh** [comment]
+1 Would love rst support.
