### ISSUE TITLE
search support

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#27]
search within pad / search across multiple pads -- both unsupported at present.

**Comment by laughinghan** [comment]
AFAIK, all the browsers good enough to support EtherPad have search built-in

**Comment by redhog** [comment]
I take this to mean full-text search among all public pads

**Comment by laughinghan** [comment]
hm, sounds interesting. Perhaps also a checkbox to choose whether to include past revisions (i.e., deleted words)
