### ISSUE TITLE
txt2tags wiki syntax import / export support

### ISSUE THREAD

**Issue by farvardin** [ether/pad#271]
A feature request: 
The txt2tags syntax is simple, efficient et allows to further export to many formats (30 targets languages in the SVN, including bbcode, markdown, wikipedia (mediawiki), docuwiki, docbook etc.)

http://txt2tags.org/

It would be so great to allow to import and especially export, from an etherpad project to the txt2tags syntax!

**Comment by JohnMcLear** [comment]
Looks pretty nice to me, < 1MB and requires python.  Can it do DocX and PDF "out of the box"?

**Comment by farvardin** [comment]
I was especially thinking to the use of the syntax within etherpad, not the full tool for exporting to other formats, but why not? 
It can't export to the proprietary docx format, but it's possible to export to RTF (in the latest svn version). PDF can be achieved by the LaTeX export of txt2tags

**Comment by JohnMcLear** [comment]
.docx is sadly extremely important for Etherpad users ;\
