### ISSUE TITLE
Sidebar resize area overlapping scrollbar and color selector

### ISSUE THREAD

**Issue by ilpssun** [ether/pad#272]
The width of the vertical bar that allows to resize the sidebar is too big.  It overlaps both the scrollbar on the left and (among other things) the color selector on the right.  The result is that clicks in the scrollbar don't scroll the document but rather enable the sidebar resizing.  The same is true for clicking the color selector.  For the latter, the workaround is to click near the right edge of the colored box; this is interpreted correctly as a click on the selector.

I have reproduced the issue in Firefox 4, IE 8 and Safari 5.0.5 (WebKit 533.21.1) - haven't tested any other browsers - running EtherPad 1.1 on a Linux host.

**Comment by azatoth** [comment]
I've the same problem, and it's really cumbersome when working with larger documents.
