### ISSUE TITLE
Long delay and very high load for generating timeline

### ISSUE THREAD

**Issue by ilpssun** [ether/pad#273]
When I try to generate a timeline for my (rather large) pad, the java process on the server goes haywire, hogging an entire virtual CPU core at 100% load for several minutes before the timeline is actually delivered and rendered in the browser.  Starting a second request makes the virtual server so slow that the EtherPad frontend loses connection to the backend.  The same issue appear when I try to load a saved revision.

I can't quite pinpoint the issue any further.  If you give me a pointer on what logs/debug messages would help, I'll be happy to provide them.

Running EtherPad 1.1 on CentOS 5.6 and  java version "1.6.0_17" OpenJDK Runtime Environment (IcedTea6 1.7.10) (rhel-1.21.b17.el5-i386)

**Comment by JohnMcLear** [comment]
What are your server specs?

**Comment by ilpssun** [comment]
We’re running CentOS 5.6 on a VMware virtual machine with 1056 MB of RAM and two virtualized Intel Pentium D CPUs @ 3.00GHz. Etherpad was compiled with Scala 2.7.7.final.  Java takes up about 240 MB of RAM according to top, no swapping as far as I can tell.  The options passed to the Java VM on the command line:
- -classpath ... 
- -server 
- -Xmx444M -Xms444M 
- -Djava.awt.headless=true 
- -XX:MaxGCPauseMillis=500 
- -XX:+UseConcMarkSweepGC 
- -XX:+CMSIncrementalMode 
- -XX:CMSIncrementalSafetyFactor=50 
- -XX:+PrintGCDetails 
- -XX:+PrintGCTimeStamps 
- -Xloggc:./data/logs/backend/jvm-gc.log 
- -Dappjet.jmxremote=true
- net.appjet.oui.main 
- --configFile=./etc/etherpad.local.properties 
- --maxThreads=111
