### ISSUE TITLE
Retrieving data

### ISSUE THREAD

**Issue by san123** [ether/pad#276]
Dear Team,

I would greatly appreciate it if you could help me with this.

I had used the public pads from etherpad.com, before it was acquired by Google. I have some important information in there, which I thought I had exported, but it turns out i haven't ( from the Chat option). Is there anyway we can go back and retrieve the data from a particular URL under etherpad.com? (etherpad.com/ <extension>).

Any help appreciated !

Thanks
San

**Comment by JohnMcLear** [comment]
No.
