### ISSUE TITLE
instruction link broken

### ISSUE THREAD

**Issue by sigmike** [ether/pad#278]
The install instructions link in the README is broken. And the installation help link from the website is scary (full of spam).

**Comment by JohnMcLear** [comment]
1. Which README?
2. Which link are you seeing spam on?  A url would be helpful.

**Comment by sigmike** [comment]
1. The root README.md: https://github.com/ether/pad/blob/master/README.md (the link is http://doc.etherpad.org/ep/tag/?query=installation)
2. My bad, it's not spam. It's just strange titles: http://doc.etherpad.org/ep/search/?query=installation (accessible from the website, Help / Installation).

**Comment by JohnMcLear** [comment]
Alright I will get onto it.

**Comment by Pita** [comment]
It redirects now

**Comment by mildsunrise** [comment]
I propose to change the link to the current repo, see #325.
