### ISSUE TITLE
main.scala

### ISSUE THREAD

**Issue by johnuren1980** [ether/pad#281]
In pad / infrastructure / net.appjet.oui / main.scala line 254, The request log timezone setting should not be hard coded here but read from the configuration file. I would suggest a fix but my scala knowledge isn't that good.

**Comment by sesam** [comment]
Direct link into the code: https://github.com/ether/pad/blob/master/infrastructure/net.appjet.oui/main.scala#L254
(And I'm no Scala-hacker either :()

**Comment by johnuren1980** [comment]
Thanks for the link.
