### ISSUE TITLE
PDF/Image not rendering for some users of SketchSpace

### ISSUE THREAD

**Issue by theoryshaw** [ether/pad#286]
In reference to the sketchSpace plugin (originally from https://github.com/redhog/pad/tree/SketchSpace.net):

For certain users, the PDF or raster image does not render in the left SketchSpace pane.  For example, as shown in the following image: http://dl.dropbox.com/u/7117445/gray%20box.jpg

The problem seems to be browser and PDF agnostic, as a number of users have experienced the problem, from various browsers and various PDF files.

**Comment by redhog** [comment]
screen capture here: 
http://ss.openingdesign.com/nvLqhSmNPY

Example problem pad: http://ss.openingdesign.com/MgLo79vYWD

No problem: Google Chrome 12.0.742.91 m
Problem: IE version 8, running on 64but Windows 7 platform

**Comment by redhog** [comment]
Person couldn't upload this pdf: http://dl.dropbox.com/u/35063877/AR3%2001B.pdf
Either it wouldn't work or it was moving so slowly that it appeared not to work.

He was using IE version 8 (8.0.6001.18702)

For someone else, this worked, but very very slowly, however, the image's aspect ratio was distorted as well.

**Comment by theoryshaw** [comment]
Thanks, Egil, for moving this stuff over. 

Let Oscia, and I know if you need any other information from the various users, to try and recreate and pinpoint the problem.
