### ISSUE TITLE
Nothing happens when click on 'share this pad'

### ISSUE THREAD

**Issue by tdesvenain** [ether/pad#288]
When i click on 'share this pad',  an overlay appears (with opacity) but it is empty

**Comment by hqdm** [comment]
Hi

i have the same issue too. Anyone an idea ?
Using version 1.1 on Debian Lenny 5.0.8 vserv

**Comment by erdgeist** [comment]
Look into https://github.com/ether/pad/issues/293 for an explanation and a patch.
