### ISSUE TITLE
"zero" theme

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#289]
The idea just occurred to me for a "zero" theme, which would look just like visiting a standard web page (no top bar, no line numbers down the side), but which would be live-editable.  All UI commands would be done by keyboard.

**Comment by JohnMcLear** [comment]
This already exists as the nano theme..  
Example: http://primarypad.com/test?_theme=nano

**Comment by holtzermann17** [comment]
Close, but there are still numbers down the left.
