### ISSUE TITLE
Etherpad Lite, No options to control font. ( Fixed, monospace should be an easy option! Maybe even some syntax extention? )

### ISSUE THREAD

**Issue by WildCryptoFox** [ether/pad#290]
Etherpad Lite ( or maybe just willyou.typewith.me ) only has the default font, no method to change it.

Maybe a line at the start or end of the file to control the font. maybe syntax highlighting could be enabled via the line too.. eg.

/\* @font:fixed; syntax:C */
# @font:fixed; syntax:shell
// @font:fixed; syntax:javascript

**Comment by sesam** [comment]
Good idea, but this is the bugtracker for Etherpad. You find Etherpad Lite at https://github.com/Pita/etherpad-lite/issues
