### ISSUE TITLE
Allow for custom defaults

### ISSUE THREAD

**Issue by tildelowengrimm** [ether/pad#298]
Etherpad doesn't currently allow for many things to be set as defaults on team sites. Things like defaulting to full screen and to monospace typeface would be brilliant, if doable.

**Comment by JohnMcLear** [comment]
afaik you can set these parameters in the URL ie http://host.com/padID?fullScreen=1

**Comment by tildelowengrimm** [comment]
Are these parameters documented anywhere?

**Comment by JohnMcLear** [comment]
http://groups.google.com/group/etherpad-dev/browse_thread/thread/a99b0f450330e8b4
