### ISSUE TITLE
text properties

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#3]
Marking a string or block of text with a certain "property".  Obvious examples exist, like underlining and italics, and user-specific colors, all exist.  Some generalizations would be colorful underlining (a la MS Word).  Highlighting a passage and put a comment in the margin is a more advanced version.

**Comment by laughinghan** [comment]
I imagine the whole attribute system could be made more modular?

**Comment by holtzermann17** [comment]
Marking this as "high priority" because many UI things (e.g. tables) would build on top of this.

**Comment by redhog** [comment]
There is now a basic implementation of this in redhog/pad. Check it out and comment on the API here!

**Comment by redhog** [comment]
Since no one seems to bother, I'm just gonna close this now...
