### ISSUE TITLE
openid consumer support for pro

### ISSUE THREAD

**Issue by Daviey** [ether/pad#30]
Maintaining separate authentication details in multiple sites is not very convenient.  It would be useful to be able to support openid as a consumer, and perhaps have support for group mappings.

**Comment by michaelforrest** [comment]
I am about to have a crack at this. Has anybody else done any work on this?

**Comment by elijh** [comment]
michael, any progress?

I have less interest in openid, per se, but it would be great to be able to plug in different authentication modules.
