### ISSUE TITLE
reversed movement with arrows in rtl languages

### ISSUE THREAD

**Issue by amiad** [ether/pad#300]
If the text is in rtl languages (Hebrew, Arabic, persian, etc.) then the movement of keyboard arrows.
If I press the right cursor moves to the left.

It's very difficult to work in Hebrew, because it.

**Comment by sesam** [comment]
Which browsers have you tried?
The editing is handled by the browser, and if the etherpad software should do workarounds they will likely have to be browser-specific.

**Comment by amiad** [comment]
Firefox 9 and 7.
On Chromium 17 the bug not happen.

**Comment by tomer** [comment]
See [issue 243](https://github.com/ether/pad/issues/243) for more requirements on RTL
