### ISSUE TITLE
Botched SSL email confirmation URL when trying to create a "team site"

### ISSUE THREAD

**Issue by AlainKnaff** [ether/pad#301]
When creating a team site, etherpad sends a confirmation mail to the e-mail address creating it.

However, if etherpad is set up on https, an extra :0 is included, which breaks the "signing" URL.

https://sub.etherpad.hitchhiker.org.lu:0/ep/account/sign-in?uid=1&tp=eQQaIRmsdf

Removing the extra :0 makes it work.

I traced this to the following code snipped in httpsHost in /usr/share/etherpad/etherpad/src/etherpad/utils.js :

  if (appjet.config.listenSecurePort != "443" && !appjet.config.hidePorts) {
   h = (h + ":" + appjet.config.listenSecurePort);
  }

Changing this to the following makes it work:

  if (appjet.config.listenSecurePort != "443" && appjet.config.listenSecurePort != "0" &&  !appjet.config.hidePorts) {
   h = (h + ":" + appjet.config.listenSecurePort);
  }

**Comment by JohnMcLear** [comment]
Done

**Comment by AlainKnaff** [comment]
Thanks :-)
