### ISSUE TITLE
etherpad/bin/run-local.sh script dependant on exact order of parameters

### ISSUE THREAD

**Issue by AlainKnaff** [ether/pad#302]
When etherpad is started, /etc/init.d/etherpad first calls /usr/share/etherpad/bin/run.sh with the equivalent of the following command line:

/usr/share/etherpad/bin/run.sh $"DAEMON_ARGS"

bin/run.sh then calls etherpad/bin/run-local.sh using the following command line:

exec bin/run-local.sh  --etherpad.soffice="$SOFFICE_BIN"  "$@" 256M

However, run-local.sh expects its parameters in a well-defined order, where --cfg (if present) must precede --etherpad.soffice .
This makes it impossible to put --cfg into DAEMON_ARGS (needed if I want to start up several instances).

Changing the last line of bin/run.sh into the following works around the issue:

exec bin/run-local.sh  "$@" --etherpad.soffice="$SOFFICE_BIN"   256M

however, this would probably break on any options that are supposed to come _after_ etherpad.soffice.

A better solution would be if run-local.sh didn't depend on the order of options:

while [ $# -gt 0 ] ; do
  case $1 in
    --etherpad.soffice)
        # do etherpad.soffice stuff with $2
        shift
        shift
        ;;
    --cfg)
         # do cfg stuff with $2
         shift
         shift
         ;;
         ...
    *)
        break
        ;;
    esac
done

**Comment by JohnMcLear** [comment]
It would be nice if you could issue a pull request with this implemented, thanks! :)

**Comment by AlainKnaff** [comment]
I'm not yet knowledgeable about git; how can I do this?

After further analysis, it turned out that the --etherpad.soffice option is not actually used by run-local.sh , so maybe run.sh should also be changed not to include it...

**Comment by JohnMcLear** [comment]
http://help.github.com/pull-requests/

-----Original Message-----

**Comment by AlainKnaff** [comment]
Done. I hope I did everything right...
