### ISSUE TITLE
"Horse blinkers" in default CSS

### ISSUE THREAD

**Issue by AlainKnaff** [ether/pad#305]
By default, etherpad's CSS has the following in /usr/share/etherpad/etherpad/src/static/css/pad2_ejs.css after line 13:
# padpage {

 position: absolute;
 top: 0px;
 bottom: 8px;
 left: 50%;
 margin-left: -450px;
 width: 900px;
}

This has the effect of making the display look "funny" on any window which is not 900 pixels wide: "horse blinkers" (unused bars left and right) on wide screens, and pad partially hidden without (!) scrollbars on small screens (such as the Nokia N900).

Just commenting out the entire paragraph makes the issue go away in both situations.

(copying the nano or micro pad2_ejs.css also solves the "horse blinkers" issue, but makes the sidebar disappear with no obvious way of making it re-appear)

**Comment by JohnMcLear** [comment]
Have you tested in all browsers?

**Comment by AlainKnaff** [comment]
tested in Firefox, Midori, Opera, Konqueror and Nokia N900

**Comment by JohnMcLear** [comment]
Afaik it is like that due to IE.

If you can put a page live I can test it w/ IETester

-----Original Message-----

**Comment by AlainKnaff** [comment]
You can visit https://etherpad.hitchhiker.org.lu/test

**Comment by JohnMcLear** [comment]
Non-full screen mode is broken.

Click Full screen in the top right corner.

-----Original Message-----

**Comment by AlainKnaff** [comment]
A ok. Yes, this fixes it. Both on wide screens and on the N900. Thanks.

But why is this not the default? Or can in be set up to be the default in /etc/etherpad/etherpad.local.properties ? If so, how?

**Comment by sesam** [comment]
There's no etherpad.local setting related to CSS/displaying for what I know. People more or less hack their template files and suffer whenever there is a central repo change to those files I guess...
What are the pros with keeping a 900px width? To make documents look equal to all visitors whatever the screen size? Perhaps there is a way to keep 900px width and do the centering-stuff with javascript and only activate for large enough screens?

**Comment by AlainKnaff** [comment]
If users want width-independent display, can't they just press <RETURN> to start a new line? Or maybe we could introduce a special "pre-formatted" mode.

Well, in any case, this doesn't seem to be an issue in Etherpad Lite, which always uses the entire window or space available.

**Comment by JohnMcLear** [comment]
Yup..
