### ISSUE TITLE
Timeslider doesn't work in some browsers

### ISSUE THREAD

**Issue by DanielO** [ether/pad#309]
The timeslider loads but stays stuck on the first revision. Clicking the play button clicks in when pressed but does nothing, and the step forward/backward buttons are greyed out. Dragging the slide does nothing (except move the slide).

Browsers where this doesn't work..
Chrome 16.0.912.41 on OSX
Firefox 3.6.24 on OSX
IE8 on Windows XP
Chrome 16.0.912.41 on Windows XP
Firefox 8.0 on OSX

I did find that Safari 5.1.1 on OSX works though..

**Comment by JohnMcLear** [comment]
Are there any javascript errors?

-----Original Message-----
From: DanielO [mailto:reply@reply.github.com]
Sent: 19 November 2011 15:52
To: John McLear
Subject: [pad] Timeslider doesn't work in some browsers (#309)

The timeslider loads but stays stuck on the first revision. Clicking the play button clicks in when pressed but does nothing, and the step forward/backward buttons are greyed out. Dragging the slide does nothing (except move the slide).

Browsers where this doesn't work..
Chrome 16.0.912.41 on OSX
Firefox 3.6.24 on OSX
IE8 on Windows XP
Chrome 16.0.912.41 on Windows XP
Firefox 8.0 on OSX

I did find that Safari 5.1.1 on OSX works though..

---

Reply to this email directly or view it on GitHub:
https://github.com/ether/pad/issues/309
This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of the organisation from which this email originated. If you are not the intended recipient of this email and its attachments, you must take no action based upon them, nor must you copy or show them to anyone. Please contact the sender if you believe you have received this email in error. This email was sent by School Email - Safe Webmail and Hosted Email for Schools;/p>

**Comment by DanielO** [comment]
Chrome shows..
Failed to load resource: the server responded with a status of 404 (Not Found)
timeslider:98
Object
data: Object
type: "CLIENT_VARS"
**proto**: Object
timeslider.js:1loading changest on startup:  0 100 
Object
timeslider.js:1response:  
Object
actualEndNum: 0
apool: Object
backwardsChangesets: Array[0]
forwardsChangesets: Array[0]
granularity: 100
start: 0
timeDeltas: Array[0]
**proto**: Object
timeslider.js:1loading changest on startup:  0 10 
Object
timeslider.js:1response:  
Object
actualEndNum: 0
apool: Object
backwardsChangesets: Array[0]
forwardsChangesets: Array[0]
granularity: 10
start: 0
timeDeltas: Array[0]
**proto**: Object
timeslider.js:1loading changest on startup:  0 1 
Object
timeslider.js:1response:  
Object
actualEndNum: 1
apool: Object
backwardsChangesets: Array[1]
forwardsChangesets: Array[1]
granularity: 1
start: 0
timeDeltas: Array[1]
**proto**: Object
timeslider.js:1adding changeset: -1 0
timeslider.js:1newRev:  0 
Object
changesets: Array[0]
fromRev: 0
rev: 0
spans: Array[0]
status: "complete"
times: Array[0]
**proto**: Object
timeslider.js:1status: complete, changesets:  [] path: 
Object
timeslider.js:1[d.fn.d.init[1], d.fn.d.init[1], d.fn.d.init[1], d.fn.d.init[1], d.fn.d.init[1], d.fn.d.init[1]]

Safari shows...
padtopback2.gifFailed to load resource: the server responded with a status of 404 (Not Found)
timeslider:98
Object
timeslider.js:1loading changest on startup:  0 100 
Object
timeslider.js:1response:  
Object
timeslider.js:1adding changeset: -1 99
timeslider.js:1adding changeset: 99 199
timeslider.js:1adding changeset: 199 299
timeslider.js:1adding changeset: 299 399
timeslider.js:1adding changeset: 399 499
timeslider.js:1adding changeset: 499 599
timeslider.js:1adding changeset: 599 699
timeslider.js:1adding changeset: 699 799
timeslider.js:1adding changeset: 799 899
timeslider.js:1loading changest on startup:  900 10 
Object
timeslider.js:1response:  
Object
timeslider.js:1adding changeset: 899 909
timeslider.js:1adding changeset: 909 919
timeslider.js:1adding changeset: 919 929
timeslider.js:1loading changest on startup:  930 1 
Object
timeslider.js:1response:  
Object
timeslider.js:1adding changeset: 929 930
timeslider.js:1adding changeset: 930 931
timeslider.js:1adding changeset: 931 932
timeslider.js:1adding changeset: 932 933
timeslider.js:1adding changeset: 933 934
timeslider.js:1adding changeset: 934 935
timeslider.js:1adding changeset: 935 936
timeslider.js:1adding changeset: 936 937
timeslider.js:1adding changeset: 937 938
timeslider.js:1newRev:  938 
Object
timeslider.js:1status: complete, changesets:  [] path: 
Object
timeslider.js:1[Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1], Object[1]]

So it would appear the JS is confused about how many changesets there are (at a guess).

**Comment by JohnMcLear** [comment]
Can you look at the net panel and see what file the 404 error is from please?

-----Original Message-----

**Comment by DanielO** [comment]
It is for https://cain.gsoft.com.au/etherpad/static/css/static/img/padtopback2.gif

**Comment by JohnMcLear** [comment]
Requires user/pass to access this.

-----Original Message-----

**Comment by DanielO** [comment]
Yes, like the rest of the etherpad :)

It's for my work so it's password protected.

The file itself doesn't exist in the etherpad-lite repo - in any case Safari also complains about it but it works.

**Comment by JohnMcLear** [comment]
Are you running the latest version of Etherpad?  Afaik I fixed that 404 issue months ago.

The apt version if probably not the latest btw.

**Comment by DanielO** [comment]
Whoops, for some reason I managed to report the bug here, but it's an etherpad-lite bug :-/

Sorry for the noise :(

**Comment by JohnMcLear** [comment]
:|

-----Original Message-----
