### ISSUE TITLE
deploy on standard ports w/o root access

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#31]
It would be good to have a way to run EtherPad on standard port numbers as a non-root user.

**Comment by sesam** [comment]
To be specific; the etherpad webservice would start with root access, bind to port 80 and quickly degrade itself to non-root.

**Comment by redhog** [comment]
This is not done in most app-servers for security reasons, better to put all eggs in one basket - nginx or apache. Setting up forwarding using one of those isn't too hard.

**Comment by penSecIT** [comment]
We will prepare an etherpad-proxy package which is provided by etherpad-authbind, etherpad-apache2 and etherpad-nginx to proxy from port 80 to the etherpad port.

Doing this for 443 would be to much work (certificate stuff) but if the user has the pattern how to proxy it will be easy for him to add the neccessary configuration options for ssl.

**Comment by redhog** [comment]
Closing as nginx and apche + and https in nginx/apache both works really nice, no need for complicating the appserver itself.
