### ISSUE TITLE
Ability to export the whole version history

### ISSUE THREAD

**Issue by eug48** [ether/pad#311]
To be able to make a backup of the pad (in case the hosting site goes down for example), it'd be very useful to be able to export the history into a version control system. For example, there could be an export option to a mercurial bundle or the git equivalent. This can also come in useful for other reasons - e.g. ability to do a "blame" search to see who added a particular line.

Thanks for you work & efforts!

**Comment by redhog** [comment]
This shouldn't be too hard, as long as the export can be in the internal changeset format. You could even provide a way to import this easily, creating a new pad instance (copy w history).

**Comment by eug48** [comment]
oh yeah, import would allow for some interesting use cases too, though it means creators can alter/fake the history..
