### ISSUE TITLE
Etherpad Lite (win) only running localhost

### ISSUE THREAD

**Issue by GregoriMarow** [ether/pad#318]
Hi

I can run my etherpad lite for windows only on localhost. When i set it up for the static ip of the server you can reach the pad, you can create a pad but the center screen shows only "loading". I can see the etherpad toolbar but i cant do anything.
For testing i have disabled the firewall, nothing changed.

But wenn i run it as localhost and open it in the servers webbrowser its working well but then i cant reach it from outside, because its binded to the localhost and if i cant reach it from the net it is senseless.

**Comment by GregoriMarow** [comment]
don't bind it to an ip... sry

**Comment by JohnMcLear** [comment]
heh
