### ISSUE TITLE
Etherpad crashes when using encoded URL

### ISSUE THREAD

**Issue by bobapple** [ether/pad#319]
If I use a encoded URL, which includes a character from the ISO/IEC 8859-1 Table that is above 7F, Etherpad will crash.

Example:

This works fine:  https://localhost/p/abc%7F123

This will let Etherpad crash: https://localhost/p/abc%80123

Version used:
commit 294029643a28f1c9468695a4ecdc58a3eb53900c
Merge: dae0cbf 1e092e3
Author: John McLear john@mclear.co.uk
Date:   Mon Aug 27 12:40:56 2012 -0700:

**Comment by JohnMcLear** [comment]
Have you considered switching to Etherpad Lite?

Date: Wed, 29 Aug 2012 02:52:37 -0700

**Comment by bobapple** [comment]
this actually happens in etherpad lite, i accidentally used the wrong bugracker
sorry for that

**Comment by JohnMcLear** [comment]
I think this got fixed as it appears to be fine now.
