### ISSUE TITLE
Ability to create read-only links that don’t allow edit access

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#32]
(can someone explain this more?--)

"could be done by having read-only links be more random and then not require pad passwords (with ability to expire/remove them)"

**Comment by sesam** [comment]
I beleive the code exists and what's missing is to make the readonly link visible.

**Comment by sesam** [comment]
Further explanation by jefferai@foundation meeting 3: 
Two things:
1. make read-only links encrypted such that you can't find the writable link from it
2. make pad passwords specific to the link, not its contents

**Comment by redhog** [comment]
This exists. Go to the time-slider view of a pad. In that view, there is a link near the top-right to "Readonly version of this pad".

This functionality is also actively used and promoted in my twitterstyle-tags patch.
