### ISSUE TITLE
EPL using way more than 30MB RAM

### ISSUE THREAD

**Issue by aicm** [ether/pad#320]
Hello,

I am trying to set ulimit to keep EPL from using over 100 MB of ram on my host but it is impossible to start EPL with any kind of memory limit under 100 - v8 errors. I was really hoping to have that light 30 MB or even 50. But if I cannot limit its memory usage at all, then it will go over what's allotted to me by the host. All I have to do is load up a test pad and type something and the memory usage bumps 20MB. That's quite a bit ...

Any ideas for me to reduce memory usage or at least keep it at a max?

**Comment by JohnMcLear** [comment]
I'm pretty sure we state on the readme page it uses 20MB ram..  But okay...  http://stackoverflow.com/questions/7193959/memory-limit-in-node-js-and-chrome-v8 might help

**Comment by aicm** [comment]
Thank you :)
