### ISSUE TITLE
Typewith.me old links

### ISSUE THREAD

**Issue by kwizrak** [ether/pad#321]
We had some old files (2011) on the typewith.me domain. Trying to open them recently I came up with the following error
Cannot GET /XXXXXXXXXX
Is there a chance of retreiving them? 

An example of these files is 
http://typewith.me/G7nGmpU73Q
I can send the whole list if needed.

**Comment by JohnMcLear** [comment]
I'd have to charge a fee to restore old pads.  You can contact me directly via email if you require this.
