### ISSUE TITLE
Can't use Mopad on Firefox

### ISSUE THREAD

**Issue by madamephilosophe** [ether/pad#322]
Sorry if this issue is listed already. 

But I tried to get on a Mopad I haven't been to in a while, that is not public. It was pressing me to do persona, but when I tried to do that it said that my browser was not supported. And I was on Firefox 15.0.1 (Mac). I upgraded to 16 and it still will not let me in. So I used Safari, and that appears to be working.

It is really weird to come to the Mozilla site and to have it tell you "Your browser isn't supported" when I am on Firefox!!!

So I have created  persona ID using safari but I would much rather use FFx. Please advise?

**Comment by JohnMcLear** [comment]
Mopad is moving to Etherpad Lite over the next few months so just sit tight and this will be resolved.
