### ISSUE TITLE
Shibboleth Authentication

### ISSUE THREAD

**Issue by reza-norouzian** [ether/pad#323]
I'm a new user in etherpad-lte and i want to authenticate users in it.
Actually i don't know how can i authenticate  users with any methods e.g. ldap in etherpad-lite, However i want to do that by Shibboleth.
Is there any shibboleth plug-in exist??
Also i need help to tell me which files in etherpad-lite should be changed or created to support authentication mechanisms.

**Comment by JohnMcLear** [comment]
We're currently working on rewriting the auth module.

**Comment by reza-norouzian** [comment]
so, how log does it take approximately?? 
I'm involved in a project that we have to use shibboleth as an authenticator.

**Comment by JohnMcLear** [comment]
Probably a few months until we have a new auth framework in place.  We are looking to find someone to lead our technical efforts in this area so if you are interested then keep an eye on the wiki because pita is due to publish a draft spec.

**Comment by JohnMcLear** [comment]
Oh I just realized this is for the old Etherpad, yeah we're not doing any work on the old Etherpad..  Heh..  See Etherpad Lite.
