### ISSUE TITLE
Etherpad is broken for browser configured with languages with missing translations

### ISSUE THREAD

**Issue by freqmod** [ether/pad#327]
Etherpad (local and beta.etherpad.org) is unusable for browser configured with languages with missing translations.
In console:
html10n.js:1 : Uncaught Error: Couldn't find translations for nb 

It does only show:
An error occured
The error was reported with the following id: 'wC6ewb7857Mvh98Sky49'

Please send this error message to us:
'ErrorId: wC6ewb7857Mvh98Sky49
URL: http://beta.etherpad.org/p/IsliUFMYJ5
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22
Uncaught TypeError: undefined is not a function in http://beta.etherpad.org/static/js/html10n.js at line 1'

**Comment by JohnMcLear** [comment]
Another one for @marcelklehr

**Comment by marcelklehr** [comment]
er.. wrong repo?
