### ISSUE TITLE
Template system

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#33]
For improved style and clean up of the HTML tags.

Simplify the css styles and the css compilation stuff.

**Comment by redhog** [comment]
Theming system where you can easily drop themes into a directoy and select theme from the config-file.

**Comment by redhog** [comment]
Implemented in latest redhog/pad

**Comment by holtzermann17** [comment]
It needs some documentation.  I see that "theme = default" in etherpad.local.properties selects the default theme -- but just what are the ingredients for a new theme?  Do I need to copy all of etherpad/src/themes/default/templates or just the stuff I want to modify?  I want to create a "minified" theme as a demo -- what's more I already have a draft of it (as a patch against an earlier version of etherpad) http://gist.github.com/368720 -- but a lot has changed.  I think if we can turn this patch into a proper theme we can close this issue.

**Comment by redhog** [comment]
At the moment you have to copy :( I would like to make themes able to inherit from each other (the basic framework with pages inheriting from other pages within a theme is already there)

**Comment by holtzermann17** [comment]
And how about CSS?  It seems that the default theme is only based on EJS.  But for example, I definitely will want to modify pad2_ejs.css.  Can I just stick it in themes/micro/css ?

**Comment by holtzermann17** [comment]
I made a branch called 'micro' that creates a new theme, and it works, except both pad2_ejs.css and pad2.js need to be changed "by hand".  (See
http://github.com/holtzermann17/pad/commit/437fb8a1159c4753bd43e0c6b0b6a1798df03567)

I think issue with pad2.js is just bad style (I'll open a separate issue about that).

Definitely would be nice if css could go into the a theme subdirectory.

**Comment by holtzermann17** [comment]
Sorry, moved that commit to here to make the network graph look nicer: http://github.com/holtzermann17/pad/commit/ae97149266ed80daa1abd17ccda57bb7532053a2

**Comment by redhog** [comment]
I'm gonna fix a themes/THEMENAME/static/js and themes/THEMENAME/static/css
