### ISSUE TITLE
Default etherpad font can`t be changed

### ISSUE THREAD

**Issue by marla47** [ether/pad#331]
Hello,

if I change the font-family in pad.css and iframe_editor.css for body, textarea, nothing happens. I restarted several times and set the cache to 0. Different font families work only for the headings.

Thanks for help in advance

**Comment by JohnMcLear** [comment]
Please upgrade.

marla47 notifications@github.com wrote:

Hello,

if I change the font-family in pad.css and iframe_editor.css for body, textarea, nothing happens. I restarted several times and set the cache to 0. Different font families work only for the headings.

Thanks for help in advance

—
Reply to this email directly or view it on GitHubhttps://github.com/ether/pad/issues/331.

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of the organisation from which this email originated. If you are not the intended recipient of this email and its attachments, you must take no action based upon them, nor must you copy or show them to anyone. Please contact the sender if you believe you have received this email in error. This email was sent by School Email - Safe Webmail and Hosted Email for Schools
