### ISSUE TITLE
doc.etherpad.org dump required

### ISSUE THREAD

**Issue by nidico** [ether/pad#333]
The etherpad instance http://doc.etherpad.org was _the_ documentation for classic etherpad and has been down . As there still exist many instances of classic etherpad, it'd be very useful to link to a dump (or even a mirror installation) of doc.etherpad.org.

Is there a dump anywhere?

If so, please add it to the README.

**Comment by nidico** [comment]
[This post](https://groups.google.com/d/msg/etherpad-open-source-discuss/p9sYl3x0JD4/OxtqWvib-WoJ) states that it has been taken down deliberately. So I hope that they did a html dump before or at least kept a backup of the database, everything else would by highly irresponsible!

**Comment by nidico** [comment]
@JohnMcLear - in [this post](https://groups.google.com/d/msg/etherpad-open-source-discuss/p9sYl3x0JD4/DbxI0-TX7IoJ) you write that you still have access to the old server. Could you please provide a dump of it?

**Comment by nidico** [comment]
@JohnMcLear - could you please answer? And please don't close unanswered issues, this pisses people off!

**Comment by JohnMcLear** [comment]
Can't help. Sorry

**Comment by nidico** [comment]
Why not? What happened with the data on the old server? It contained a lot of valuable information IIRC contributed by many people.

**Comment by JohnMcLear** [comment]
Because I can't.  Sorry
