### ISSUE TITLE
Are there maintained forks? If so, please add them to README

### ISSUE THREAD

**Issue by nidico** [ether/pad#334]
It's a pitty classic etherpad isn't developed anymore, it was a very nice peace of free software, and has many great features, which etherpad-lite still doesn't have yet.

Does anybody know of a maintained fork? [SviMik/pad](https://github.com/SviMik/pad) and [mozilla/pad](https://github.com/mozilla/pad) shows quite regular and current activity, but don't have the Github issue tracker enabled. I also don't know if the changes are useful for the general public or just for a specific instance.

If there's an at least somewhat maintained fork, this repo should link to it in the README.

**Comment by rhelmer** [comment]
mozilla/pad is not maintained, I don't suggest using it (unless you want to fork and audit it), Mozilla uses etherpad-lite now.

**Comment by nidico** [comment]
[SviMik/pad](https://github.com/SviMik/pad) has updated their README. It contains customizations, so it's not supposed to be "the maintained version of etherpad classic".

Still, critical things (security, performance) are supposed to be fixed (haven't tested yet), so it might be a good upgrade choice for those who maintain existing etherpad classic installations, and also for new interested users. I will post back when I find the time to try it out.

**Comment by leanderme** [comment]
I started to update some of the dependencies. Most of them where simple replacements without any modifications needed. 
I recently tried to update jetty (from 6 to 9). For this, major modifications are necessary as jetty has evolved / changed significantly. Is anyone interested in collaborating on this?

**Comment by nidico** [comment]
> Is anyone interested in collaborating on this?

I can't help as I don't have any knowledge of the stack and have no time to dive into it.

But if you manage to run Etherpad on an updated stack, I'd be very happy to test it, as I'm still running an old instance (now using [SviMik/pad](https://github.com/SviMik/pad)), which I'd very much like to upgrade to a newer stack.

Maybe someone at [titanpad/titanpad](https://github.com/titanpad/titanpad) is also interested in an upgrade or might help out with this.

**Comment by JohnMcLear** [comment]
Not me.
