### ISSUE TITLE
Sync offline work

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#34]
Sometimes people will want to edit offline, and sync/import content (cf. Git!).

**Comment by zeigerpuppy** [comment]
would be very useful, this could be implemented most simply by having a tool that runs a diff on imported files and shows any conflicts for the author to approve/reject and then tags edits with the author's colour.

**Comment by cscott** [comment]
The repo at https://github.com/JohnMcLear/ep_offline_edit seems like it is relevant?

**Comment by JohnMcLear** [comment]
@cscott offline edit is more for being able to still access your data offline in case you get disconnected.  The actual editor isn't available yet.  I have a good idea for how to accomplish offline editing but for now and until I can secure some budget/funding we're stuck with copy/paste.

**Comment by JohnMcLear** [comment]
Closing this as a wont-fix
