### ISSUE TITLE
watches

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#39]
Be notified when a given pad changes.

**Comment by holtzermann17** [comment]
e.g., on Mac OS X, growl notifications of changes, see http://growl.info/about.php

**Comment by holtzermann17** [comment]
Or RSS for the web-based world.

**Comment by holtzermann17** [comment]
Cain suggested: Is it possible to have the RSS feed highlight changes since the last version you contributed to? the last time you contributed would have to be stored somewhere, then the old version pulled from archive, but PHP could generate a kind of dynamic RSS couldn’t it, which highlights changes since you last contribute?

**Comment by redhog** [comment]
There is no PHP anywhere near this code, but it can be done for sure (using server side javascript :)

**Comment by redhog** [comment]
This exists in a limited form for public pads in the twitterStyleTags plugin.
