### ISSUE TITLE
image support

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#4]
This could start with simple things like support for rendering external images "inline",
then move on to more complicated things like magazine-style inset images.

**Comment by JohnMcLear** [comment]
I'd like to see an images plugin but not in core, the main reason for that is the "weight" of images and asking js to cache images could be painful

**Comment by laughinghan** [comment]
generalized inline embedded thingies -- images, tables, or editable math thing (what I'm working on) -- would be nice.

**Comment by holtzermann17** [comment]
can you send me some more info about your editable math thingy? - holtzermann17 at gmail

**Comment by michaelforrest** [comment]
I've implemented this as a plugin - it just detects png or jpg files and renders the image inline: http://github.com/michaelforrest/pad/tree/master/etherpad/src/plugins/showImages/ 
I also made an 'insert image' button that sits in the main codebase but all it does is sticks the image url in the pad body... the icon took me a while though :-s

**Comment by redhog** [comment]
This works wonderfully together with the fileUpload plugin :)
