### ISSUE TITLE
etherpad running as an interface to git 

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#42]
Pads committing changes to a file in a git repo!

**Comment by penSecIT** [comment]
Would be nice, yes, but probalby impossible because of the internal layout of how etherpad stores data.

Even a port from MySQL to postgres is hard and (afaik) not yet finished.

**Comment by mikkorantalainen** [comment]
How about committing to a git repository when hitting the "save" icon?

Etherpad contains already parts to successfully export the contents to DOC/ODT/PDF so it should be possible to export some kind of text output to a file and do "git add filename; git commit -m 'Version saved by A.U. Thor'.

In the future, if etherpad is able to display differences between two saved versions, it could automatically display the diff when hitting the "save" icon and ask for a commit message (if configured for git backend).

**Comment by canadaduane** [comment]
I like mikko's take on this.  Git should not be concerned with the micro-deltas that etherpad stores internally--only the larger scale "saved states" that a user cares to signal explicitly.  Having a file-based backend like this would make it even more useful to outside tools.

**Comment by dangayle** [comment]
+1
I know this is an old issue, but I'd love to see someone take on Mikko's idea for etherpad-lite

**Comment by JohnMcLear** [comment]
This is the old Etherpad repo, if you want this I'd suggest creating a new issue for it over at this bug tracker:
https://github.com/ether/etherpad-lite/issues

and also create a vote for it at:
http://etherpad.idea.informer.com/

**Comment by JohnMcLear** [comment]
Actually implementing this wouldn't be too tough in theory, it'd be very little work compared to some projects we do.

**Comment by JohnMcLear** [comment]
Closing this as a wont-fix as it should be worked on in etherpad lite
