### ISSUE TITLE
easier install

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#44]
- Decent script to check environment variables during install
- Simple install script
- Could we go as far as a package, added to a repository? (For linux-based setups)

**Comment by holtzermann17** [comment]
I've put together a compiled set of installation instructions based on existing instructions out on the web, http://wiki.github.com/ether/pad/installation-instructions-ii
The only problem is, this set of instructions is already out of date (specifically, globals.js doesn't control the superdomains anymore).  Maintaining an up-to-date INSTALL.txt file would be a good first step towards maintaining an up-to-date install script.

**Comment by redhog** [comment]
The software is now packaged for Debian/Ubuntu, and has build/run scripts that autodetects most setups. Windows isn't included thou.
