### ISSUE TITLE
Branching Time Slider

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#48]
Compare Github's graph.

**Comment by holtzermann17** [comment]
Marking as high-priority (among "hard as hell" issues).  If we ever get a Summer of Code intern or someone looking for a thesis topic, maybe we should invite them to tackle this.

**Comment by redhog** [comment]
This can, because of "hard as hell", not be 1.1 material.

**Comment by holtzermann17** [comment]
right, that's why it's 2.0 :)

**Comment by redhog** [comment]
This could be an extension of #56 btw...
