### ISSUE TITLE
Better styling

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#5]
Clean up the nasty html and id-based specialized css and replace by more generic stuff.

**Comment by holtzermann17** [comment]
Furthermore, it would be great if we could disentangle the CSS and the javascript a bit further, as in the case of pad_editor.js line 119, where the size of a deltaBottom comes into play in the layout of things.

That sort of mechanics seems to break modularity and prevent us from providing a simple configuration file to specify the UI.

**Comment by redhog** [comment]
Yeah. Even the simple fact that layout is done with JavaScript, not CSS is rather stuffed up to begin with, and stuffs up modularity.

Esp. when we start to add UI elements using plugins, this hard-codedness is gonna bite us :(
