### ISSUE TITLE
wordcount and other stats

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#51]
Wordcount and perhaps other statistics in the sidebar.

**Comment by avtobiff** [comment]
Character count would be good. Motivation is that news papers and such have requirements on this statistic.

**Comment by dchandler** [comment]
It seems like this shouldn't be too tricky of a thing to add on. Would having to calculate the statistics create too much of a burden though on etherpad?

**Comment by tekacs** [comment]
@dchandler: It may seem so, but couldn't this simply be done client-side in JS, removing the need for the server to calculate these things?
