### ISSUE TITLE
assess contributions as percentages

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#52]
Ability to measure the contribution of specific users as a percentage (possible uses are inside the classroom where I personally see the most potential for Etherpad) this would assist teachers to assess contribution to group work.

(Useful both on a specific pad and bloc-wide, which indicates that we need user homepages!)

**Comment by dchandler** [comment]
To build upon this idea --- it would be fantastic to have basic statistics like:
- Total edit time on pad
- % of time editting from both people (sums to >100%)
- Chatting behavior (# of lines, % of time, # words etc.)

Also, a visual representation may be useful. I am providing a link to an article that describes the LS graph (Figure 6) -- http://dl.dropbox.com/u/5021551/Lindgren%20and%20Sullivan%202002.pdf. I will also create an issue/feature request for an LS graph in a separate ticket.

The LS graph displays a lot of information at once -- total characters typed over time, total characters that remain, where a user is editing, and when a "revision" occurs. Pedagogically speaking, there are plenty of writing researchers who have observed that showing students graphs like this can greatly improve how they write.

For example, this curve can show students their "writing strategy" -- are they planners? do they make edits as they go and obtain a perfect 1st draft? is their first draft "sloppy" and do they like to edit at the end? Etc.

In short, it's a way to have a conversation about how a student writes. The LS graph described in the paper is only for one user, but could be extended with multiple people quite easily.
