### ISSUE TITLE
fork pads

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#56]
I’d like a “copy this pad” button, even for read-only pads, where the pad that got copied retains a list of links to copies. This allows people to continue working on read-only stuff, effectively forking it, w/o disturbing the original, but still having their copies findable by people who know about the original.

**Comment by aribn** [comment]
Here's how I'm handling it: http://gist.github.com/596981

**Comment by redhog** [comment]
This is in 1.1 :) Thanks aribn, I just had to pluginify your code and that was all...
