### ISSUE TITLE
api for basic editing features

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#57]
API to fetch, append, prepend, search & replace (...).

**Comment by redhog** [comment]
Exists in the ACE. But maybe you meant a JSON/XML-RPC API, not just an API?

**Comment by holtzermann17** [comment]
This would be something to look at for purposes of comparison: http://gobby.0x539.de/trac/wiki/APIReference

**Comment by holtzermann17** [comment]
Anyway, yeah, I think a JSON API would be what we're after.  Also it would be nice to better document the API we do have.

**Comment by redhog** [comment]
Well... JsDoc Kit?
JSON shouldn't be that hard since we have fastjson available on the server...
Question is how much of the editing API is available on the server?

**Comment by canadaduane** [comment]
Is there currently a way to simply read the content of a document, via some sort of REST API?

**Comment by redhog** [comment]
http://piratepad.net/ep/pad/export/ro.6d78iSj8xyO/rev.8?format=html
gives you a simple HTML version of the contents of revision 8. latest can also be used instead of a specific revision.

**Comment by prauscher** [comment]
The API should be able to generate Pads (both private and public pads) and set the contents of the Pad. "API-Codes" for private Pads would be great.
