### ISSUE TITLE
make edit work on android

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#60]
Currently view works, just edit doesn’t.

**Comment by redhog** [comment]
Does Android have JavaScript support at all?

**Comment by JohnMcLear** [comment]
Whistles innocently

**Comment by AlexanderS** [comment]
At least android 2.0 supports javascript. It uses the same engine like chrome (the famous v8).

**Comment by redhog** [comment]
Ok, cool, so let's debug it :)
