### ISSUE TITLE
Debian Package for Easy Installation

### ISSUE THREAD

**Issue by brianherman** [ether/pad#63]
Could you please create a debian package for easy installation.
I would but I dont know how.

**Comment by brianherman** [comment]
Please!

**Comment by sesam** [comment]
This is related to the issue #44

**Comment by Daviey** [comment]
I am happy to work on this, and get it sponsored into Debian.  However, I do not have the time to be the sole maintainer.

**Comment by avtobiff** [comment]
I have filed an ITP bug (Intend To Package, http://bugs.debian.org/576998) for this and also posted to the etherpad-dev mailing list.

**Comment by redhog** [comment]
Please see http://webapps-common.alioth.debian.org/draft/html/ch-issues.html for information in file-hierarchy requirements of debian, ubuntu and even rh for web applications
