### ISSUE TITLE
Let the user change page title

### ISSUE THREAD

**Issue by sesam** [ether/pad#64]
If the page TITLE could be changed, then you could find which is which between many open tabs of pads.

Let the user easily re-title the page.  We have so many windows/pages open, it's helpful if the page title isn't just 'EtherPad: CPRlj1ir7s'.   Also, when we bookmark a page, it's nice if the bookmark shows a nice human-readable name immediately.

Suggestion for how:  Inside the page in the blue bar where it says "EtherPad" now, slide that to the left and put the title there.  Users can click to edit the title text, and it should update the page title.

**Comment by redhog** [comment]
You could just use the first line of the pad? That way editing the title will work just like editing anything else (and should really update everyones title-bar in real time!).

**Comment by sesam** [comment]
The title should probably go inside DIV#docbarpadtitle, which on all etherpad installations I've seen so far contains an icon with tooltip "Public Pad: Public Pad" and a regular text "Public Pad". There might already be some sourcecode aspiring to do this.

Mockup: function x_changeTitle(e) { if (!e) return; var elt=e.srcElement, title=prompt('Change Title?',elt.textContent); if (title) elt.textContent=elt.title=document.title=title;} document.getElementById('docbarpadtitle').onclick=x_changeTitle;

Next step: Store the title in DB when changed, and read it back when document gets opened. (Will this auto-sync to all users if one user changes the title?)

**Comment by redhog** [comment]
To do db sync _outside_ of the pad would be a lot of extra work I guess...

Why not just use the first line of the pad, but display it in the docbar too, and update that as the pad is updated?

**Comment by sesam** [comment]
Some title-functionality is already in there!?

http://github.com/ether/pad/blob/master/etherpad/src/etherpad/pad/padevents.js#L115

else if (msg.type == "padtitle") {
    if (msg.title && padutils.isProPadId(pad.getId())) {
      pro_padmeta.accessProPad(pad.getId(), function(propad) {
        propad.setTitle(String(msg.title).substring(0, 80));

**Comment by redhog** [comment]
hm, true, for pro pads... maybe you could use the same, but still, a pad would need two different titles - the URL ID and the display title. Would those two have to be the same for pro pads, or could you edit both in that case?
