### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by sesam** [ether/pad#65]
Control-B for boldfacing works if you have some text selected.  It should also work when you have nothing selected:  set the font options for what I'm about to type.  Same for Control-I italics, Control-U underlining. (Perhaps this already works? Or might be a browser-dependent issue.)

**Comment by holtzermann17** [comment]
Maybe we could base this on KeySnail for Firefox?  In any case, the #1
keyboard command I would like would be one for following
links!

**Comment by redhog** [comment]
This is really a bit hard, as there is no "currently selected attributes", but the attributes of the surrounding text is copied to newly inserted text. Also, text is inserted directly by the browser, as pure text, and only later reformatted/attributed by an event handler. So there is no way to e.g. distinguish a copy/paste from simple typing...
