### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by redhog** [ether/pad#67]
Installer for windows, preferably without cygwin

**Comment by holtzermann17** [comment]
High priority, because right now there is nothing else having to do with installation.

**Comment by JohnMcLear** [comment]
This could be something we do in a day in October.  I am pretty familiar w/ this and I can also do NSIS.  The bit that confused me was the jar stuff.

**Comment by JohnMcLear** [comment]
Just an update on this, 

We updated the docs that cover Cygwin here: http://mclear.co.uk/2010/02/18/installing-etherpad-on-windows-cygwin/

I'm expecting Joyent and Microsoft to bring NodeJS to Windows pretty sharpish so that will be my focus for getting Etherpad onto Windows
