### ISSUE TITLE
XMPP gateway for the chat

### ISSUE THREAD

**Issue by redhog** [ether/pad#68]
Add integration with external chat-clients using XMPP

**Comment by holtzermann17** [comment]
Marking this as high-priority because it seems like it would be useful.  (Among other things, it could be an additional way to implement "watches", i.e. in addition to RSS.)

**Comment by marxistvegan** [comment]
@JohnMcLear why was this set to wontfix?

**Comment by JohnMcLear** [comment]
@marxistvegan this repo is dead, no development happens here, all development happens on the new etherpad repo

http://github.com/ether/etherpad-lite
