### ISSUE TITLE
View/Edit Source

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#7]
It would be nice to be able to get at the underlying XML (it is XML, right?)
so that we can edit it with an external editor.  Exposing the clickstream (er,
keypress-stream) to other programs as a web service in real time would be
great!

**Comment by redhog** [comment]
It is _not_ xml, for good reasons (performance). See http://doc.etherpad.org/OVV8zvUQa1 for details. Exposing the clickstream should be rather easy and can be done in the collab lib.
