### ISSUE TITLE
Realtime information sharing between multiple etherpads

### ISSUE THREAD

**Issue by Intensity** [ether/pad#71]
I'd like to choose a subset of a pad (A) and display that subset within another pad (B), such that changes entered from either of the pads are automatically updated in the other pad.  The idea could be nested.  Of course it would be important to avoid cases where recursion could occur, or to decide to respond canonically to those cases in a deterministic way.

It would also be great to implement the ability to "fold" portions of the text (once it has been classed as a proper subset of the original pad) so that the user sees a stub in place of the folded text if they prefer.

A flexible access mechanism could be created whereby a user is given permission to read, write, export a subset of a document, share, and so on.  Once that infrastructure is in place, then the subset of a document could be accessible by others from various destination pads according to those finely grained criteria.

**Comment by holtzermann17** [comment]
http://en.wikipedia.org/wiki/Transclusion
