### ISSUE TITLE
sweep for hard-coded numbers and settings

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#72]
There are various places in the code where a
hard-coded number is used to specify something
that should probably be a variable that can be
set from a config file.  

In the case of CSS files, hard-coded values may
be entirely appropriate, but they should still be
documented.

Keep in mind that any fixed number in the code basically
plays the same role as a global variable.   If we're going
to use them, we had better explain them!

**Comment by dchandler** [comment]
This is really important. Especially in terms of figuring out how these could potentially be put into javascript controls such as: http://groups.google.com/group/etherpad-dev/browse_thread/thread/a99b0f450330e8b4
