### ISSUE TITLE
problem with tag search?

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#74]
http://doc.etherpad.org/X8UXsfoIFa
isn't found by running
http://doc.etherpad.org/ep/tag/?query=this-isnt-saved

**Comment by redhog** [comment]
The pad lacks the #public tag. This is not a bug, it's a feature.

**Comment by holtzermann17** [comment]
Well, unfortunately I _meant_ for them to be public, but I didn't know about that tag.  Now I wonder if there is a way for me to recover all of the pages that include the tag #manual-section (even though they don't include the #public tag) so that I don't have to make them all over again!

**Comment by redhog** [comment]
if you have access to the database, you can search in the TAG and PAD_TAG tables by hand (the database schema should be sort of self-explanatory).

**Comment by holtzermann17** [comment]
I think the rather essential nature of the #public tag should be documented
a bit better; and, given that it is so essential, I think it need's further
fleshing out.  For example, #public is in contrast to a "#private" default;
Etherpad should know what my private pads are via a cookie or something?

**Comment by redhog** [comment]
This definitely needs (more) documenting, but it was one of the main requirements when developing it, that it be made really hard to accidentally make a page public e.g. by including something that just happened to look like a tag.

A #private tag wouldn't really do that trick.

This, btw is why #public is colored differently from all other tags (as is #writable).

The best solution in my opinion is to include a text about this in the default pad content (what comes up when you create a pad), as well as the tags #public and #writable at the bottom, making all new pads public and publicly writable by default (until that line is removed by the user that is)

**Comment by redhog** [comment]
The cookie idea is actually a good one, could you make a separate issue of that?

If we had a cookie of private pads, we could allow people to search among those even thou they're private :)
