### ISSUE TITLE
Writeup on AppJet vs node.js

### ISSUE THREAD

**Issue by sesam** [ether/pad#75]
The idea is to investigate and write something on whether AppJet could benefit from node.js.
Would a reimplementation be possible? Useful? (Is node.js mature enough?)

Working document is at http://doc.etherpad.org/gzei9nxQzJ

**Comment by holtzermann17** [comment]
I think this is interesting, since it could significantly impact performance.

**Comment by tekacs** [comment]
For that matter, this would also open up some more hosting options, as well as possibly improving performance, as mentioned...

**Comment by redhog** [comment]
node.js is another framework similar to AppJet, solving the same problem, but with a very different API. Rewriting Etherpad for Node.JS from AppJet would be a huge task, and quite pointless.

**Comment by tekacs** [comment]
That's very true - it's definitely 'hard as hell' - this would only be worth considering if, for example, AppJet threw up some significant problems that we weren't expecting... For that matter, it's also worth bearing in mind that AppJet isn't, in and of itself, supported any more (as far as I know) and so there's the potential that at some point, bringing AppJet up to date may become more difficult than porting to Node, so I think it's worth remembering, but not an immediate priority in any way... :)

**Comment by redhog** [comment]
Well, "we are AppJet" now :)I think one of our future goals should be to separate out the AppJet code from the ACE and Etherpad code chunks, and provide them as three separate products. But already this would pose some problems; just to figure out which files can safely be removed is quite a task.

**Comment by tekacs** [comment]
That's true - the big advantage of node.js, of course, is the huge momentum built up behind it. As such, if maintaining AppJet ever becomes _too great_ a task, a port would perhaps be a feasible option, especially with the _huge_ backing that node has. On the other hand, a port would be a great deal of work and for the moment, separating out AppJet is definitely the way to go... While it's a large task, it's probably for the better in the long run...

Edit:
Also, I'd volunteer to do this myself, only I'm not sure I'll have a chance to do so for quite a while yet... Any volunteers?
