### ISSUE TITLE
cookie for keeping track of private pads

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#76]
Keeping track of the users private pads would allow me to search through all the pads
I had created, even when they are not public.

See discussion at http://github.com/ether/pad/issues/issue/74#issue/74/comment/184564

**Comment by redhog** [comment]
Simple description of implementation: Put a cookie on users' computer that contains a list of all visited pad IDs. Allow the user to select to search among these pads in addition to #public pads in the tag search.

Extension: Allow a user to import all pads linked in a pad into his/her cookie without actually opening them, as well as pasting links to all cookie-content pads into a new pad.
