### ISSUE TITLE
SECURITY: jBCrypt < 0.3 weak hashes if password contains non us-ascii characters

### ISSUE THREAD

**Issue by avtobiff** [ether/pad#78]
Read more at http://www.mindrot.org/files/jBCrypt/internat.adv

I have updated my fork with a jBCrypt 0.3 jar and requested a pull.

**Comment by sesam** [comment]
Fixed in http://github.com/ether/pad/commit/5698f2dc1372c1df8e0d94a7cf3bf04519820b94

**Comment by holtzermann17** [comment]
Presumably that means we should close this issue?

**Comment by avtobiff** [comment]
Yes, close this issue.

**Comment by sesam** [comment]
Closed
