### ISSUE TITLE
multi-directional scrolling

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#8]
Right now, Etherpad only has a sense of line numbers and scrolling up and down.
Add column numbers and left-right scrolling.

**Comment by redhog** [comment]
How would the column numbering work with proportional font and with the auto-line-wrapping currently in place?

**Comment by holtzermann17** [comment]
Not very well. 

To briefly expand on the original idea, I was thinking about a 'full screen' version of Etherpad, and about moving chunks of text around like Post-It^tm notes.  Other programs already do a nice GUI version of a 'desktop' (e.g. Balsamiq uses this for
drag-and-drop creation of mockups), but a text-based version of a 'shared desktop'
would still be quite novel, I think.
