### ISSUE TITLE
jQuery versions

### ISSUE THREAD

**Issue by sesam** [ether/pad#81]
src/static/js/ contains several versions of jQuery.
Figure out which one(s) we need
Bonus question: Would we like to upgrade to something newer than 1.3.2 dated 2009-02-19 ?

**Comment by holtzermann17** [comment]
See also http://github.com/ether/pad/issues#issue/73

**Comment by sfreilich** [comment]
Etherpad repo currently includes three different versions of jquery.  And there are two copies of 1.2.1.

```
# find -iname 'jquery-*.js'
./etherpad/src/static/js/jquery-1.2.6.js
./etherpad/src/static/js/jquery-1.3.2.js
./infrastructure/ace/build/jquery-1.2.1.js
./infrastructure/ace/www/jquery-1.2.1.js
```
