### ISSUE TITLE
Move out to properties-file in etc/

### ISSUE THREAD

**Issue by sesam** [ether/pad#83]
from collab/server_utils.js:

/// Begin readonly/padId conversion code
/// TODO: refactor into new file?
var _baseRandomNumber = 0x123123; // keep this number seekrit

**Comment by redhog** [comment]
Also make the install script generate this.
Note however that this security is susceptible to a known-plain-text attack: The key is constant and the attacker can create any number of pads (even with a name of their own choosing) and access the corresponding read only link.
