### ISSUE TITLE
email sends out email w/ port 9000 so links dont work if you have apache in front of etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [ether/pad#87]

**Comment by jefferai** [comment]
Use hidePorts = true in your config file.

**Comment by JohnMcLear** [comment]
worked a treat, documented here:
http://mclear.co.uk/2010/05/06/etherpad-emails-show-wrong-port-9000-when-sending-from-version-1-running-apache-and-mod_proxy/
and here:
http://doc.etherpad.org/wrong-port
