### ISSUE TITLE
checkHost() redirects to etherpad.com

### ISSUE THREAD

**Issue by pajoma** [ether/pad#92]
If the checkHost() method in src/main.js (line 279) fails, it will redirect to etherpad.com. It should actually redirect to the domain specified in the properties file.

**Comment by nigelbabu** [comment]
Aren't more than one domains specified in the properties file?  How would this be sorted in that case?

**Comment by nigelbabu** [comment]
What I mean is the install instructions say

Example: topdomains = yourhostname.com,localhost

How would one figure out which is the right one?
