### ISSUE TITLE
RSS feed of changes of a pad

### ISSUE THREAD

**Issue by redhog** [ether/pad#95]
RSS feed of changes of a particular pad (even private pads and readonly pads)

**Comment by holtzermann17** [comment]
Marking this as high priority, because other items in the DB category seem a bit goofy, whereas this one seems really useful.

**Comment by tekacs** [comment]
Hmm, but how often do updates get published? On every saved revision?

**Comment by redhog** [comment]
That's not how RSS works. The RSS stream is generated whenever the client requests it.  The publish dates for "articles" are the time of the last changes of the pads, and the publish time for the whole RSS is the last such time.

**Comment by tekacs** [comment]
Yes, but RSS consists of articles and I was wondering how often 'articles' would be 'published' - in that, when a client requested the RSS feed, I wondered how many articles would appear - one for each revision (i.e. lots and lots of articles) or one for each _saved_ revision (i.e. fewer, more useful articles, perhaps?).

And yes, for the record, I know (I think fairly well) how RSS works... :P

**Comment by redhog** [comment]
One for each pad, and with a publish date of the last revision. This means that each edit becomes a _change_ to an article in RSS, not a new post.

**Comment by timmfin** [comment]
You could also have digest feeds that summarize changes made to a pad for a time period X (over a day, week, month, etc). Even if the digest feed didn't have a complete diff of changes, it would be useful to know that Y users edited a pad yesterday/last week/etc.
