### ISSUE TITLE
tag browser: no more choices => different message?

### ISSUE THREAD

**Issue by holtzermann17** [ether/pad#96]
The box that contains the text

"Search for pads that have the tag [...]
Search for pads that don't have the tag [..]"

should maybe have a more obvious message when the listing
can't be refined further (i.e. when all of the tags are
the same) and we're just left with the message

"Search for pads that have the tag
Search for pads that don't have the tag"

**Comment by sesam** [comment]
guilty code is in a plugin: twitter-style-tags
